//! Formats a plan as Rust source.

use std::fmt::Write;

use turbojet_dictionary::Dictionary;

use crate::plan::{Plan, Presence, Struct};

pub(crate) fn root(dict: &Dictionary) -> String {
    format!(
        "//! Generated by turbojet-codegen from the {} dictionary. Don't edit: regenerate.\n\n\
         pub mod enums;\npub mod groups;\npub mod messages;\npub mod tags;\n\n\
         pub use enums::*;\npub use groups::*;\npub use messages::*;\n",
        dict.version
    )
}

pub(crate) fn tags(plan: &Plan) -> String {
    let mut out = String::from("//! Tag numbers, one per dictionary field.\n\n");
    for (constant, name, tag) in &plan.tags {
        writeln!(out, "/// {name}({tag}).\npub const {constant}: u32 = {tag};").unwrap();
    }
    out
}

pub(crate) fn enums(plan: &Plan) -> String {
    let mut out = String::from("//! Enumerated fields.\n");
    for e in &plan.enums {
        out.push_str("\nturbojet::fix_enum! {\n");
        doc_comment(&mut out, "    ", &e.doc);
        writeln!(out, "    {} {{", e.name).unwrap();
        for v in &e.variants {
            if let Some(doc) = &v.doc {
                doc_comment(&mut out, "        ", doc);
            }
            writeln!(out, "        {} = {:?},", v.name, v.code).unwrap();
        }
        out.push_str("    }\n}\n");
    }
    out
}

pub(crate) fn groups(plan: &Plan) -> String {
    let mut out = String::from("//! Repeating-group entries.\n");
    out.push_str(&imports(plan, &plan.groups.iter().collect::<Vec<_>>(), false));
    for group in &plan.groups {
        write_struct(&mut out, "fix_group", &group.name, group);
    }
    out
}

pub(crate) fn messages(plan: &Plan) -> String {
    let mut out = String::from("//! Application messages.\n");
    let defs: Vec<&Struct> = plan.messages.iter().map(|m| &m.def).collect();
    out.push_str(&imports(plan, &defs, true));
    for m in &plan.messages {
        write_struct(&mut out, "fix_message", &format!("{} = {:?}", m.def.name, m.msg_type), &m.def);
    }
    out
}

/// The `use` lines the structs need, and no more (unused imports would warn).
fn imports(plan: &Plan, structs: &[&Struct], groups_module: bool) -> String {
    let slots = || structs.iter().flat_map(|s| &s.slots);
    let mut out = String::from("\n");
    // The type names in a slot's type, e.g. `Vec`, `Code` and `Side` in `Vec<Code<Side>>`.
    let names = || slots().flat_map(|s| s.ty.split(['<', '>', ' ', ',']).filter(|name| !name.is_empty()));
    if names().any(|name| plan.enums.iter().any(|e| e.name == name)) {
        out.push_str("use super::enums::*;\n");
    }
    if groups_module && slots().any(|s| s.presence.is_group()) {
        out.push_str("use super::groups::*;\n");
    }
    if !structs.is_empty() {
        out.push_str("use super::tags::*;\n");
    }
    const FIELD_TYPES: [&str; 9] = [
        "Code",
        "Decimal",
        "MonthYear",
        "NaiveDate",
        "Secret",
        "TzTimeOnly",
        "TzTimestamp",
        "UtcTimeOnly",
        "UtcTimestamp",
    ];
    let types: Vec<&str> = FIELD_TYPES.into_iter().filter(|t| names().any(|name| name == *t)).collect();
    match types.as_slice() {
        [] => {}
        [one] => writeln!(out, "use turbojet::fields::{one};").unwrap(),
        many => writeln!(out, "use turbojet::fields::{{{}}};", many.join(", ")).unwrap(),
    }
    out
}

fn write_struct(out: &mut String, macro_name: &str, head: &str, s: &Struct) {
    writeln!(out, "\nturbojet::{macro_name}! {{").unwrap();
    doc_comment(out, "    ", &s.doc);
    writeln!(out, "    {head} {{").unwrap();
    for slot in &s.slots {
        doc_comment(out, "        ", &slot.doc);
        let tags = match &slot.length {
            Some(length) => format!("{length} => {}", slot.tag),
            None => slot.tag.clone(),
        };
        writeln!(out, "        {}: {} {} = {tags},", slot.ident, slot.presence.keyword(), slot.ty).unwrap();
    }
    out.push_str("    }\n}\n");

    // new(required fields and groups, in slot order)
    let params: Vec<String> = s
        .slots
        .iter()
        .filter_map(|f| match f.presence {
            Presence::Req if f.ty == "String" || f.ty == "Secret" || f.ty.starts_with("Code<") => {
                Some(format!("{}: impl Into<{}>", f.ident, f.ty))
            }
            Presence::Req | Presence::Data => Some(format!("{}: {}", f.ident, f.ty)),
            Presence::ReqGroup => Some(format!("{}: Vec<{}>", f.ident, f.ty)),
            Presence::Opt | Presence::Group | Presence::OptData => None,
        })
        .collect();
    let inits: Vec<String> = s
        .slots
        .iter()
        .map(|f| match f.presence {
            Presence::Req if f.ty == "String" || f.ty == "Secret" || f.ty.starts_with("Code<") => {
                format!("{0}: {0}.into()", f.ident)
            }
            Presence::Req | Presence::ReqGroup | Presence::Data => f.ident.clone(),
            Presence::Opt | Presence::OptData => format!("{}: None", f.ident),
            Presence::Group => format!("{}: Vec::new()", f.ident),
        })
        .collect();
    write!(
        out,
        "\nimpl {name} {{\n    /// With the required fields and groups; optional ones empty.\n    \
         #[allow(clippy::too_many_arguments, clippy::new_without_default)]\n    \
         pub fn new({params}) -> Self {{\n        Self {{ {inits} }}\n    }}\n}}\n",
        name = s.name,
        params = params.join(", "),
        inits = inits.join(", "),
    )
    .unwrap();
}

/// A `///` line per line of `doc`; an empty line separates paragraphs.
fn doc_comment(out: &mut String, indent: &str, doc: &str) {
    for line in doc.lines() {
        if line.is_empty() {
            writeln!(out, "{indent}///").unwrap();
        } else {
            writeln!(out, "{indent}/// {line}").unwrap();
        }
    }
}
