//! Formats a laid-out SBE schema as Rust.

use std::collections::{BTreeSet, HashSet};
use std::fmt::Write;

use super::schema::{Block, Composite, Enum, Group, Kind, Message, Presence, Prim, Schema, Set, Slot};
use crate::Error;
use crate::naming::{field_ident, ident, type_in_use};

/// Why writing generated code can't fail: it goes into a `String`.
const INFALLIBLE: &str = "writing to a String cannot fail";

/// The runtime the generated code calls, by full path so no schema name can shadow it.
const RT: &str = "turbojet::sbe";

/// A type name: `messageHeader` → `MessageHeader`, `ExecutionReport_New` → `ExecutionReportNew`,
/// `FALSE_VALUE` → `FalseValue`. Words in capitals are capitalised; others keep their case.
pub(crate) fn type_name(name: &str) -> String {
    let mut out = String::new();
    for word in name.split('_').filter(|w| !w.is_empty()) {
        let shouting = word.len() > 1 && !word.chars().any(|c| c.is_ascii_lowercase());
        let mut chars = word.chars();
        let first = chars.next().expect("words aren't empty");
        out.push(first.to_ascii_uppercase());
        if shouting {
            out.extend(chars.map(|c| c.to_ascii_lowercase()));
        } else {
            out.extend(chars);
        }
    }
    if out.starts_with(|c: char| c.is_ascii_digit()) { format!("V{out}") } else { out }
}

/// Renders a schema, tracking the names it gives out and the helpers it needs.
pub(crate) struct Renderer<'s> {
    schema: &'s Schema,
    get: &'static str,
    put: &'static str,
    /// Group readers and writers needed, by dimension composite.
    dimensions: BTreeSet<String>,
    /// Data readers and writers needed, by length type.
    lengths: BTreeSet<&'static str>,
    types: HashSet<String>,
    out: String,
}

impl<'s> Renderer<'s> {
    pub(crate) fn new(schema: &'s Schema) -> Self {
        let (get, put) = if schema.big_endian { ("get_be", "put_be") } else { ("get_le", "put_le") };
        Self {
            schema,
            get,
            put,
            dimensions: BTreeSet::new(),
            lengths: BTreeSet::new(),
            types: HashSet::new(),
            out: String::new(),
        }
    }

    pub(crate) fn render(mut self) -> Result<String, Error> {
        let s = self.schema;
        writeln!(
            self.out,
            "// Generated by turbojet-codegen from the SBE schema {:?} (ID {}, version {}). Don't edit: regenerate.\n\n\
             /// The schema's ID, which each message header carries.\npub const SCHEMA_ID: u16 = {};\n\
             /// The schema's version, which encoded messages carry.\npub const SCHEMA_VERSION: u16 = {};",
            s.package, s.id, s.version, s.id, s.version
        )
        .expect(INFALLIBLE);
        for e in &s.enums {
            self.enumeration(e)?;
        }
        for set in &s.sets {
            self.set(set)?;
        }
        for c in &s.composites {
            self.composite(c)?;
        }
        for m in &s.messages {
            self.message(m)?;
        }
        self.decode()?;
        self.helpers();
        Ok(self.out)
    }

    /// Claims a type name, failing if it's taken or would shadow a type the code uses.
    fn claim(&mut self, name: &str) -> Result<String, Error> {
        let rust = ident(type_name(name));
        if type_in_use(&rust) || !self.types.insert(rust.clone()) {
            return Err(Error(format!("{name} would be generated as {rust}, which is already a type")));
        }
        Ok(rust)
    }

    fn enumeration(&mut self, e: &Enum) -> Result<(), Error> {
        let name = self.claim(&e.name)?;
        let raw = e.encoding.rust();
        let mut variants = Vec::new();
        for (value, literal) in &e.values {
            let variant = ident(type_name(value));
            if variant == "Unknown" || variants.iter().any(|(v, _)| *v == variant) {
                return Err(Error(format!("enum {}: value {value} can't be a variant", e.name)));
            }
            variants.push((variant, literal));
        }
        let out = &mut self.out;
        writeln!(out, "\n/// `{}`.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum {name} {{", e.name)
            .expect(INFALLIBLE);
        for ((variant, literal), (value, _)) in variants.iter().zip(&e.values) {
            writeln!(out, "    /// `{value}` ({literal}).\n    {variant},").expect(INFALLIBLE);
        }
        writeln!(out, "    /// A value the schema doesn't list.\n    Unknown({raw}),\n}}\n\nimpl {name} {{")
            .expect(INFALLIBLE);
        writeln!(out, "    /// The value `raw` stands for.\n    #[must_use]\n    pub fn from_raw(raw: {raw}) -> Self {{\n        match raw {{")
            .expect(INFALLIBLE);
        for (variant, literal) in &variants {
            writeln!(out, "            {literal} => Self::{variant},").expect(INFALLIBLE);
        }
        writeln!(out, "            other => Self::Unknown(other),\n        }}\n    }}\n").expect(INFALLIBLE);
        writeln!(
            out,
            "    /// Its value on the wire.\n    #[must_use]\n    pub fn raw(self) -> {raw} {{\n        match self {{"
        )
        .expect(INFALLIBLE);
        for (variant, literal) in &variants {
            writeln!(out, "            Self::{variant} => {literal},").expect(INFALLIBLE);
        }
        writeln!(out, "            Self::Unknown(raw) => raw,\n        }}\n    }}\n}}").expect(INFALLIBLE);
        Ok(())
    }

    fn set(&mut self, set: &Set) -> Result<(), Error> {
        let name = self.claim(&set.name)?;
        let raw = set.encoding.rust();
        let out = &mut self.out;
        writeln!(
            out,
            "\n/// `{}`: a set of choices, one bit each.\n#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]\n\
             pub struct {name}(pub {raw});\n\nimpl {name} {{",
            set.name
        )
        .expect(INFALLIBLE);
        for (choice, bit) in &set.choices {
            let method = field_ident(choice);
            let plain = method.trim_start_matches("r#");
            let mask = if *bit == 0 { "1".to_string() } else { format!("1 << {bit}") };
            writeln!(
                out,
                "    /// Whether `{choice}` (bit {bit}) is chosen.\n    #[must_use]\n    pub fn {method}(self) -> bool {{\n        \
                 self.0 & ({mask}) != 0\n    }}\n\n    /// With `{choice}` (bit {bit}) chosen or not.\n    #[must_use]\n    \
                 pub fn with_{plain}(self, on: bool) -> Self {{\n        if on {{ Self(self.0 | ({mask})) }} else {{ Self(self.0 & !({mask})) }}\n    }}"
            )
            .expect(INFALLIBLE);
        }
        writeln!(out, "}}").expect(INFALLIBLE);
        Ok(())
    }

    fn composite(&mut self, c: &Composite) -> Result<(), Error> {
        let name = self.claim(&c.name)?;
        let (wire, constants): (Vec<&Slot>, Vec<&Slot>) =
            c.members.iter().partition(|m| m.presence != Presence::Constant);
        let mut fields = String::new();
        let (mut decode, mut encode) = (String::new(), String::new());
        for m in &wire {
            let field = field_ident(&m.name);
            let ty = self.owned_type(m)?;
            writeln!(fields, "    /// `{}`.\n    pub {field}: {ty},", m.name).expect(INFALLIBLE);
            writeln!(decode, "            {field}: {},", self.read_owned(m, "bytes")?).expect(INFALLIBLE);
            writeln!(encode, "        {}", self.write(m, "bytes", &format!("self.{field}"))?).expect(INFALLIBLE);
        }
        let derive = if wire.iter().any(|m| self.has_float(m)) { "PartialEq" } else { "PartialEq, Eq, Hash" };
        let out = &mut self.out;
        writeln!(out, "\n/// `{}`.\n#[derive(Debug, Clone, Copy, {derive})]\npub struct {name} {{\n{fields}}}", c.name)
            .expect(INFALLIBLE);
        writeln!(out, "\nimpl {name} {{\n    /// Its size on the wire.\n    pub const SIZE: usize = {};", c.size)
            .expect(INFALLIBLE);
        for m in &constants {
            let (ty, value) = self.constant(m)?;
            let constant = crate::naming::constant(&m.name);
            writeln!(self.out, "    /// `{}`, which is constant.\n    pub const {constant}: {ty} = {value};", m.name)
                .expect(INFALLIBLE);
        }
        let bytes = if wire.is_empty() { "_bytes" } else { "bytes" };
        writeln!(
            self.out,
            "\n    /// Reads it from the start of `bytes`.\n    ///\n    /// # Panics\n    ///\n    /// If `bytes` is shorter than \
             [`Self::SIZE`].\n    #[must_use]\n    pub fn decode({bytes}: &[u8]) -> Self {{\n        Self {{\n{decode}        }}\n    }}\n\n    \
             /// Writes it at the start of `bytes`.\n    ///\n    /// # Panics\n    ///\n    /// If `bytes` is shorter than \
             [`Self::SIZE`].\n    pub fn encode(&self, {bytes}: &mut [u8]) {{\n{encode}    }}\n}}"
        )
        .expect(INFALLIBLE);
        Ok(())
    }

    fn has_float(&self, slot: &Slot) -> bool {
        match &slot.kind {
            Kind::Prim { prim, .. } | Kind::Array { prim, .. } => prim.is_float(),
            Kind::Composite { name } => self.composite_named(name).members.iter().any(|m| self.has_float(m)),
            _ => false,
        }
    }

    fn composite_named(&self, name: &str) -> &'s Composite {
        self.schema.composites.iter().find(|c| c.name == name).expect("composites are laid out")
    }

    /// The type a slot is held as in a composite or a struct to encode.
    fn owned_type(&self, slot: &Slot) -> Result<String, Error> {
        let ty = match &slot.kind {
            Kind::Prim { prim, .. } => prim.rust().to_string(),
            Kind::Chars { len, .. } => format!("[u8; {len}]"),
            Kind::Array { prim, len } => format!("[{}; {len}]", prim.rust()),
            Kind::Enum { name, .. } | Kind::Set { name, .. } | Kind::Composite { name } => ident(type_name(name)),
        };
        let optional = slot.presence == Presence::Optional
            && !matches!(slot.kind, Kind::Array { .. } | Kind::Set { .. } | Kind::Composite { .. });
        Ok(if optional { format!("Option<{ty}>") } else { ty })
    }

    /// An expression reading a slot from `buf` as its owned type.
    fn read_owned(&self, slot: &Slot, buf: &str) -> Result<String, Error> {
        let (get, off) = (self.get, slot.offset);
        let optional = slot.presence == Presence::Optional;
        Ok(match &slot.kind {
            Kind::Prim { prim, null, .. } => {
                let read = format!("{RT}::{get}::<{}>({buf}, {off})", prim.rust());
                match (optional, prim.is_float()) {
                    (false, _) => read,
                    (true, true) => format!("Some({read}).filter(|v| !v.is_nan())"),
                    (true, false) => format!("Some({read}).filter(|v| *v != {null})"),
                }
            }
            Kind::Chars { len, .. } => {
                let read = format!("{buf}[{off}..{}].try_into().expect(\"a slice of {len}\")", off + len);
                if optional { format!("Some({read}).filter(|c: &[u8; {len}]| c[0] != 0)") } else { read }
            }
            // Bytes are copied as they are.
            Kind::Array { prim: Prim::U8, len } => {
                format!("{buf}[{off}..{}].try_into().expect(\"a slice of {len}\")", off + len)
            }
            Kind::Array { prim, .. } => {
                let at = element_offset(off, prim.size());
                format!("std::array::from_fn(|i| {RT}::{get}::<{}>({buf}, {at}))", prim.rust())
            }
            Kind::Enum { name, encoding, null, .. } => {
                let (ty, read) = (ident(type_name(name)), format!("{RT}::{get}::<{}>({buf}, {off})", encoding.rust()));
                if optional {
                    format!("Some({read}).filter(|raw| *raw != {null}).map({ty}::from_raw)")
                } else {
                    format!("{ty}::from_raw({read})")
                }
            }
            Kind::Set { name, encoding } => {
                format!("{}({RT}::{get}::<{}>({buf}, {off}))", ident(type_name(name)), encoding.rust())
            }
            Kind::Composite { name } => {
                let at = if off == 0 { buf.to_string() } else { format!("&{buf}[{off}..]") };
                format!("{}::decode({at})", ident(type_name(name)))
            }
        })
    }

    /// A statement writing `value`, of the slot's owned type, into `buf`.
    fn write(&self, slot: &Slot, buf: &str, value: &str) -> Result<String, Error> {
        let (put, off) = (self.put, slot.offset);
        let optional = slot.presence == Presence::Optional;
        Ok(match &slot.kind {
            Kind::Prim { null, prim, .. } => {
                let null = if prim.is_float() { format!("{}::NAN", prim.rust()) } else { null.clone() };
                let value = if optional { format!("{value}.unwrap_or({null})") } else { value.to_string() };
                format!("{RT}::{put}({buf}, {off}, {value});")
            }
            Kind::Chars { len, .. } => {
                let range = format!("{buf}[{off}..{}]", off + len);
                if optional {
                    format!("if let Some(c) = &{value} {{ {range}.copy_from_slice(c); }}")
                } else {
                    format!("{range}.copy_from_slice(&{value});")
                }
            }
            Kind::Array { prim: Prim::U8, len } => format!("{buf}[{off}..{}].copy_from_slice(&{value});", off + len),
            Kind::Array { prim, .. } => {
                let at = element_offset(off, prim.size());
                format!("for (i, v) in {value}.iter().enumerate() {{ {RT}::{put}({buf}, {at}, *v); }}")
            }
            Kind::Enum { name, null, .. } => {
                let raw = if optional {
                    format!("{value}.map_or({null}, {}::raw)", ident(type_name(name)))
                } else {
                    format!("{value}.raw()")
                };
                format!("{RT}::{put}({buf}, {off}, {raw});")
            }
            Kind::Set { .. } => format!("{RT}::{put}({buf}, {off}, {value}.0);"),
            Kind::Composite { .. } => {
                let at = if off == 0 { buf.to_string() } else { format!("&mut {buf}[{off}..]") };
                format!("{value}.encode({at});")
            }
        })
    }

    /// A constant slot's type and value.
    fn constant(&self, slot: &Slot) -> Result<(String, String), Error> {
        Ok(match &slot.kind {
            Kind::Prim { prim, constant: Some(value), .. } => (prim.rust().to_string(), value.clone()),
            Kind::Chars { constant: Some(text), .. } => {
                if !text.is_ascii() {
                    return Err(Error(format!("constant {} isn't ASCII", slot.name)));
                }
                ("&'static [u8]".to_string(), format!("b{text:?}"))
            }
            Kind::Enum { name, constant: Some(variant), .. } => {
                let ty = ident(type_name(name));
                (ty.clone(), format!("{ty}::{}", ident(type_name(variant))))
            }
            _ => return Err(Error(format!("{} is constant but has no value", slot.name))),
        })
    }

    fn message(&mut self, m: &Message) -> Result<(), Error> {
        self.block(&m.name, &m.block, Some(m.id))
    }

    /// The decoder and the struct to encode for a message's root (with its template ID) or a
    /// group entry, and then its groups'.
    fn block(&mut self, name: &str, block: &Block, template: Option<u16>) -> Result<(), Error> {
        let owned = self.claim(name)?;
        let decoder = self.claim(&format!("{name}Ref"))?;
        let mut names = HashSet::from(["sbe_block".to_string(), "sbe_version".to_string()]);
        for member in block
            .fields
            .iter()
            .map(|f| &f.name)
            .chain(block.groups.iter().map(|g| &g.name))
            .chain(block.data.iter().map(|d| &d.name))
        {
            if !names.insert(field_ident(member)) {
                return Err(Error(format!("{name}: two members would be named {}", field_ident(member))));
            }
        }
        for group in &block.groups {
            self.dimensions.insert(group.dimension.clone());
        }
        for data in &block.data {
            self.lengths.insert(data.length.rust());
        }
        let block_entries: Vec<(String, &Group)> =
            block.groups.iter().map(|g| (format!("{name}{}", type_name(&g.name)), g)).collect();
        self.decoder(name, &decoder, block, &block_entries, template)?;
        self.encoder(name, &owned, block, &block_entries, template)?;
        for (entry, group) in &block_entries {
            self.block(entry, &group.block, None)?;
        }
        Ok(())
    }

    fn decoder(
        &mut self,
        name: &str,
        decoder: &str,
        block: &Block,
        entries: &[(String, &Group)],
        template: Option<u16>,
    ) -> Result<(), Error> {
        let what = template.map_or_else(|| format!("A `{name}` entry"), |id| format!("`{name}` (template {id})"));
        let mut fields = String::new();
        for (entry, group) in entries {
            writeln!(fields, "    {}: {RT}::Group<'a, {}Ref<'a>>,", field_ident(&group.name), ident(type_name(entry)))
                .expect(INFALLIBLE);
        }
        for data in &block.data {
            writeln!(fields, "    {}: &'a [u8],", field_ident(&data.name)).expect(INFALLIBLE);
        }
        writeln!(
            self.out,
            "\n/// {what}, read where it lies.\n#[derive(Clone, Copy)]\npub struct {decoder}<'a> {{\n    sbe_block: &'a [u8],\n    \
             sbe_version: u16,\n{fields}}}"
        )
        .expect(INFALLIBLE);
        self.wrap(decoder, block, entries);
        self.accessors(decoder, block, entries)?;
        self.debug(decoder, block)?;
        Ok(())
    }

    /// The decoder's `Block::wrap`: checks the block, then reads the groups and data after it.
    fn wrap(&mut self, decoder: &str, block: &Block, entries: &[(String, &Group)]) {
        let mut needed: Vec<(u16, usize)> = Vec::new();
        for field in &block.fields {
            let end = field.offset + field.size;
            match needed.iter_mut().find(|(since, _)| *since == field.since) {
                Some((_, max)) => *max = (*max).max(end),
                None => needed.push((field.since, end)),
            }
        }
        needed.sort_unstable();
        // A version needs every field up to it.
        let mut running = 0;
        let mut needed_expr = String::new();
        for (since, end) in &needed {
            running = running.max(*end);
            needed_expr = if *since == 0 {
                running.to_string()
            } else {
                format!("if version >= {since} {{ {running} }} else {{ {needed_expr} }}")
            };
        }
        if needed_expr.is_empty() {
            needed_expr.push('0');
        }
        let uses_version =
            !entries.is_empty() || needed.iter().any(|(s, _)| *s > 0) || block.data.iter().any(|d| d.since > 0);
        let version = if uses_version { "version" } else { "_version" };
        let mut body = String::new();
        let mut members = vec!["sbe_block".to_string(), format!("sbe_version: {version}")];
        for (entry, group) in entries {
            let field = field_ident(&group.name);
            let read = format!(
                "read_{}::<{}Ref<'a>>(bytes, at, version)?",
                crate::naming::snake(&group.dimension),
                ident(type_name(entry))
            );
            body.push_str(&since_guard(&field, group.since, &read, &format!("{RT}::Group::empty()")));
            members.push(field);
        }
        for data in &block.data {
            let field = field_ident(&data.name);
            let read = format!("read_data_{}(bytes, at)?", data.length.rust());
            body.push_str(&since_guard(&field, data.since, &read, "&[][..]"));
            members.push(field);
        }
        writeln!(
            self.out,
            "\nimpl<'a> {RT}::Block<'a> for {decoder}<'a> {{\n    #[allow(clippy::too_many_lines)]\n    fn wrap(bytes: &'a [u8], block_length: usize, {version}: u16) -> Result<(Self, usize), {RT}::SbeError> {{\n        \
             let sbe_block = {RT}::take(bytes, 0, block_length)?;\n        let needed = {needed_expr};\n        if block_length < needed {{\n            \
             return Err({RT}::SbeError::BlockLength {{ actual: block_length, needed }});\n        }}\n        let at = block_length;\n{body}        \
             Ok((Self {{ {} }}, at))\n    }}\n}}",
            members.join(", ")
        )
        .expect(INFALLIBLE);
    }

    fn accessors(&mut self, decoder: &str, block: &Block, entries: &[(String, &Group)]) -> Result<(), Error> {
        let mut out = format!(
            "\n// The methods are named after the schema's fields, whatever their names suggest to clippy.\n\
             #[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]\nimpl<'a> {decoder}<'a> {{\n    /// The schema version it was encoded in.\n    pub fn sbe_version(&self) -> u16 {{\n        self.sbe_version\n    }}\n\n"
        );
        for field in &block.fields {
            let method = field_ident(&field.name);
            let doc = doc(&field.name, field.id);
            let (ty, body) =
                if field.presence == Presence::Constant { self.constant(field)? } else { self.borrowed(field)? };
            writeln!(out, "    /// {doc}\n    pub fn {method}(&self) -> {ty} {{\n        {body}\n    }}\n")
                .expect(INFALLIBLE);
        }
        for (entry, group) in entries {
            let method = field_ident(&group.name);
            writeln!(
                out,
                "    /// {}\n    pub fn {method}(&self) -> {RT}::Group<'a, {}Ref<'a>> {{\n        self.{method}\n    }}\n",
                doc(&group.name, group.id),
                ident(type_name(entry))
            )
            .expect(INFALLIBLE);
        }
        for data in &block.data {
            let method = field_ident(&data.name);
            writeln!(
                out,
                "    /// {}\n    pub fn {method}(&self) -> &'a [u8] {{\n        self.{method}\n    }}\n",
                doc(&data.name, data.id)
            )
            .expect(INFALLIBLE);
        }
        out.push('}');
        writeln!(self.out, "{out}").expect(INFALLIBLE);
        Ok(())
    }

    /// A decoder accessor's type and body for a field on the wire. Char arrays read as their
    /// text, and a field newer than the message's version reads as absent.
    fn borrowed(&self, field: &Slot) -> Result<(String, String), Error> {
        let optional = field.presence == Presence::Optional;
        let (ty, read) = if let Kind::Chars { len, .. } = &field.kind {
            let read = format!("{RT}::chars(&self.sbe_block[{}..{}])", field.offset, field.offset + len);
            if optional {
                ("Option<&'a [u8]>".to_string(), format!("Some({read}).filter(|c| !c.is_empty())"))
            } else {
                ("&'a [u8]".to_string(), read)
            }
        } else {
            (self.owned_type(field)?, self.read_owned(field, "self.sbe_block")?)
        };
        Ok(match (field.since, ty.starts_with("Option<")) {
            (0, _) => (ty, read),
            (since, true) => (ty, format!("if self.sbe_version >= {since} {{ {read} }} else {{ None }}")),
            (since, false) => (format!("Option<{ty}>"), format!("(self.sbe_version >= {since}).then(|| {read})")),
        })
    }

    fn debug(&mut self, decoder: &str, block: &Block) -> Result<(), Error> {
        let mut fields = String::new();
        let members = block
            .fields
            .iter()
            .map(|f| &f.name)
            .chain(block.groups.iter().map(|g| &g.name))
            .chain(block.data.iter().map(|d| &d.name));
        for member in members {
            let method = field_ident(member);
            writeln!(fields, "            .field({:?}, &self.{method}())", method.trim_start_matches("r#"))
                .expect(INFALLIBLE);
        }
        writeln!(
            self.out,
            "\nimpl std::fmt::Debug for {decoder}<'_> {{\n    #[allow(clippy::too_many_lines)]\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{\n        \
             f.debug_struct({decoder:?})\n{fields}            .finish()\n    }}\n}}"
        )
        .expect(INFALLIBLE);
        Ok(())
    }

    fn encoder(
        &mut self,
        name: &str,
        owned: &str,
        block: &Block,
        entries: &[(String, &Group)],
        template: Option<u16>,
    ) -> Result<(), Error> {
        let lifetime = if needs_lifetime(block) { "<'a>" } else { "" };
        let what = template.map_or_else(|| format!("A `{name}` entry"), |id| format!("`{name}` (template {id})"));
        let mut fields = String::new();
        for field in block.fields.iter().filter(|f| f.presence != Presence::Constant) {
            writeln!(
                fields,
                "    /// {}\n    pub {}: {},",
                doc(&field.name, field.id),
                field_ident(&field.name),
                self.owned_type(field)?
            )
            .expect(INFALLIBLE);
        }
        for (entry, group) in entries {
            let entry_lifetime = if needs_lifetime(&group.block) { "<'a>" } else { "" };
            writeln!(
                fields,
                "    /// {}\n    pub {}: &'a [{}{entry_lifetime}],",
                doc(&group.name, group.id),
                field_ident(&group.name),
                ident(type_name(entry))
            )
            .expect(INFALLIBLE);
        }
        for data in &block.data {
            writeln!(fields, "    /// {}\n    pub {}: &'a [u8],", doc(&data.name, data.id), field_ident(&data.name))
                .expect(INFALLIBLE);
        }
        writeln!(
            self.out,
            "\n/// {what}, to encode.\n#[derive(Debug, Clone, PartialEq)]\npub struct {owned}{lifetime} {{\n{fields}}}"
        )
        .expect(INFALLIBLE);
        let anonymous = if lifetime.is_empty() { "" } else { "<'_>" };
        writeln!(
            self.out,
            "\nimpl {owned}{anonymous} {{\n    /// The length of its block.\n    pub const BLOCK_LENGTH: usize = {};",
            block.block_length
        )
        .expect(INFALLIBLE);
        if let Some(id) = template {
            self.encode_into(id, block.block_length);
        }
        self.encode_body(block, entries)?;
        writeln!(self.out, "}}").expect(INFALLIBLE);
        if let Some(id) = template {
            writeln!(
                self.out,
                "\nimpl {RT}::Encode for {owned}{anonymous} {{\n    const TEMPLATE_ID: u16 = {id};\n\n    \
                 fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), {RT}::SbeError> {{\n        \
                 {owned}::encode_into(self, out)\n    }}\n}}"
            )
            .expect(INFALLIBLE);
        }
        Ok(())
    }

    fn encode_into(&mut self, template: u16, block_length: usize) {
        let header = ident(type_name(&self.schema.header));
        writeln!(
            self.out,
            "    /// Its template ID.\n    pub const TEMPLATE_ID: u16 = {template};\n\n    \
             /// Appends it to `out`, after a message header.\n    ///\n    /// # Errors\n    ///\n    \
             /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.\n    \
             pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), {RT}::SbeError> {{\n        let start = out.len();\n        \
             let header = {header} {{ block_length: {block_length}, template_id: {template}, schema_id: SCHEMA_ID, version: SCHEMA_VERSION }};\n        \
             header.encode({RT}::reserve(out, {header}::SIZE));\n        let result = self.encode_body(out);\n        \
             if result.is_err() {{\n            out.truncate(start);\n        }}\n        result\n    }}\n"
        )
        .expect(INFALLIBLE);
    }

    fn encode_body(&mut self, block: &Block, entries: &[(String, &Group)]) -> Result<(), Error> {
        let mut body = String::new();
        let wire: Vec<&Slot> = block.fields.iter().filter(|f| f.presence != Presence::Constant).collect();
        let reserve = format!("{RT}::reserve(out, {})", block.block_length);
        if wire.is_empty() {
            writeln!(body, "        {reserve};").expect(INFALLIBLE);
        } else {
            writeln!(body, "        let block = {reserve};").expect(INFALLIBLE);
        }
        for field in &wire {
            writeln!(body, "        {}", self.write(field, "block", &format!("self.{}", field_ident(&field.name)))?)
                .expect(INFALLIBLE);
        }
        for (entry, group) in entries {
            let field = field_ident(&group.name);
            writeln!(
                body,
                "        write_{}(out, {:?}, {}::BLOCK_LENGTH, self.{field}.len())?;\n        for entry in self.{field} {{\n            entry.encode_body(out)?;\n        }}",
                crate::naming::snake(&group.dimension),
                group.name,
                ident(type_name(entry))
            )
            .expect(INFALLIBLE);
        }
        for data in &block.data {
            let max = data.max.clone().unwrap_or_else(|| format!("{}::MAX", data.length.rust()));
            writeln!(
                body,
                "        write_data_{}(out, {:?}, self.{}, {max})?;",
                data.length.rust(),
                data.name,
                field_ident(&data.name)
            )
            .expect(INFALLIBLE);
        }
        writeln!(
            self.out,
            "    #[allow(clippy::too_many_lines)]\n    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), {RT}::SbeError> {{\n{body}        Ok(())\n    }}"
        )
        .expect(INFALLIBLE);
        Ok(())
    }

    /// `Decoded` and `decode`: a message by its template ID.
    fn decode(&mut self) -> Result<(), Error> {
        self.claim("Decoded")?;
        let header = ident(type_name(&self.schema.header));
        let mut variants = String::new();
        let mut arms = String::new();
        for m in &self.schema.messages {
            let (variant, decoder) = (ident(type_name(&m.name)), ident(type_name(&format!("{}Ref", m.name))));
            writeln!(variants, "    /// `{}`.\n    {variant}({decoder}<'a>),", m.name).expect(INFALLIBLE);
            writeln!(
                arms,
                "        {} => {{\n            let (message, len) = <{decoder} as {RT}::Block>::wrap(body, block_length, header.version)?;\n            \
                 (Decoded::{variant}(message), len)\n        }}",
                m.id
            )
            .expect(INFALLIBLE);
        }
        writeln!(
            self.out,
            "\n/// A message of this schema, as [`decode`] found it.\n#[derive(Debug, Clone, Copy)]\npub enum Decoded<'a> {{\n{variants}}}\n\n\
             /// Reads the message at the start of `bytes`: its header, then the message its template ID names. Returns the message and \
             its length, header included.\n///\n/// # Errors\n///\n/// If the header names another schema or an unknown template, or the \
             message doesn't fit in `bytes`.\n#[allow(clippy::too_many_lines)]\npub fn decode(bytes: &[u8]) -> Result<(Decoded<'_>, usize), {RT}::SbeError> {{\n    \
             let header = {header}::decode({RT}::take(bytes, 0, {header}::SIZE)?);\n    if header.schema_id != SCHEMA_ID {{\n        \
             return Err({RT}::SbeError::SchemaId(header.schema_id));\n    }}\n    let body = &bytes[{header}::SIZE..];\n    \
             let block_length = usize::from(header.block_length);\n    let (message, len) = match header.template_id {{\n{arms}        \
             id => return Err({RT}::SbeError::UnknownTemplate(id)),\n    }};\n    Ok((message, {header}::SIZE + len))\n}}"
        )
        .expect(INFALLIBLE);
        Ok(())
    }

    /// The readers and writers for the group dimensions and data lengths the blocks use.
    fn helpers(&mut self) {
        for dimension in &self.dimensions {
            let (ty, snake) = (ident(type_name(dimension)), crate::naming::snake(dimension));
            let composite = self.composite_named(dimension);
            let prim_of = |member: &str| {
                let slot = composite.members.iter().find(|m| m.name == member).expect("dimensions are checked");
                match slot.kind {
                    Kind::Prim { prim, .. } => prim.rust(),
                    _ => unreachable!("dimensions are checked"),
                }
            };
            let (block_type, count_type) = (prim_of("blockLength"), prim_of("numInGroup"));
            writeln!(
                self.out,
                "\nfn read_{snake}<'a, E: {RT}::Block<'a>>(bytes: &'a [u8], at: usize, version: u16) -> Result<({RT}::Group<'a, E>, usize), {RT}::SbeError> {{\n    \
                 let dimension = {ty}::decode({RT}::take(bytes, at, {ty}::SIZE)?);\n    let at = at + {ty}::SIZE;\n    \
                 let rest = bytes.get(at..).ok_or({RT}::SbeError::Truncated)?;\n    \
                 let (group, len) = {RT}::Group::scan(rest, {RT}::length(dimension.block_length)?, {RT}::length(dimension.num_in_group)?, version)?;\n    \
                 Ok((group, at + len))\n}}\n\n\
                 fn write_{snake}(out: &mut Vec<u8>, name: &'static str, block_length: usize, count: usize) -> Result<(), {RT}::SbeError> {{\n    \
                 let dimension = {ty} {{\n        block_length: {RT}::count(name, block_length, {block_type}::MAX)?,\n        \
                 num_in_group: {RT}::count(name, count, {count_type}::MAX)?,\n    }};\n    \
                 dimension.encode({RT}::reserve(out, {ty}::SIZE));\n    Ok(())\n}}"
            )
            .expect(INFALLIBLE);
        }
        for length in &self.lengths {
            let size = Prim::size_of_rust(length);
            writeln!(
                self.out,
                "\nfn read_data_{length}(bytes: &[u8], at: usize) -> Result<(&[u8], usize), {RT}::SbeError> {{\n    \
                 let len = {RT}::length({RT}::{get}::<{length}>({RT}::take(bytes, at, {size})?, 0))?;\n    \
                 Ok(({RT}::take(bytes, at + {size}, len)?, at + {size} + len))\n}}\n\n\
                 fn write_data_{length}(out: &mut Vec<u8>, name: &'static str, data: &[u8], max: {length}) -> Result<(), {RT}::SbeError> {{\n    \
                 let len = {RT}::count(name, data.len(), max)?;\n    {RT}::{put}({RT}::reserve(out, {size}), 0, len);\n    \
                 out.extend_from_slice(data);\n    Ok(())\n}}",
                get = self.get,
                put = self.put,
            )
            .expect(INFALLIBLE);
        }
    }
}

/// `let field = …;` reading a group or data field, or its empty value when the message's version
/// predates it. Rebinds `at` to the position after it.
fn since_guard(field: &str, since: u16, read: &str, empty: &str) -> String {
    if since == 0 {
        format!("        let ({field}, at) = {read};\n")
    } else {
        format!("        let ({field}, at) = if version >= {since} {{ {read} }} else {{ ({empty}, at) }};\n")
    }
}

/// The offset of an array's element `i`, as Rust, without arithmetic that does nothing.
fn element_offset(offset: usize, size: usize) -> String {
    match (offset, size) {
        (0, 1) => "i".to_string(),
        (0, size) => format!("i * {size}"),
        (offset, 1) => format!("{offset} + i"),
        (offset, size) => format!("{offset} + i * {size}"),
    }
}

/// A struct with groups or data borrows them.
fn needs_lifetime(block: &Block) -> bool {
    !block.groups.is_empty() || !block.data.is_empty()
}

/// A field's doc line: its schema name and ID.
fn doc(name: &str, id: Option<u32>) -> String {
    match id {
        Some(id) => format!("`{name}` ({id})."),
        None => format!("`{name}`."),
    }
}

impl Prim {
    /// The size of the primitive a length's Rust type names.
    fn size_of_rust(rust: &str) -> usize {
        match rust {
            "u8" => 1,
            "u16" => 2,
            _ => 4,
        }
    }
}
