// Generated by turbojet-codegen from the SBE schema "FIXP" (ID 2748, version 0). Don't edit: regenerate.

/// The schema's ID, which each message header carries.
pub const SCHEMA_ID: u16 = 2748;
/// The schema's version, which encoded messages carry.
pub const SCHEMA_VERSION: u16 = 0;

/// `FlowType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FlowType {
    /// `Recoverable` (0).
    Recoverable,
    /// `Idempotent` (1).
    Idempotent,
    /// `Unsequenced` (2).
    Unsequenced,
    /// `None` (3).
    None,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl FlowType {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            0 => Self::Recoverable,
            1 => Self::Idempotent,
            2 => Self::Unsequenced,
            3 => Self::None,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::Recoverable => 0,
            Self::Idempotent => 1,
            Self::Unsequenced => 2,
            Self::None => 3,
            Self::Unknown(raw) => raw,
        }
    }
}

/// `NegotiationRejectCode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NegotiationRejectCode {
    /// `Credentials` (0).
    Credentials,
    /// `FlowTypeNotSupported` (1).
    FlowTypeNotSupported,
    /// `DuplicateId` (2).
    DuplicateId,
    /// `Unspecified` (3).
    Unspecified,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl NegotiationRejectCode {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            0 => Self::Credentials,
            1 => Self::FlowTypeNotSupported,
            2 => Self::DuplicateId,
            3 => Self::Unspecified,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::Credentials => 0,
            Self::FlowTypeNotSupported => 1,
            Self::DuplicateId => 2,
            Self::Unspecified => 3,
            Self::Unknown(raw) => raw,
        }
    }
}

/// `EstablishmentRejectCode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EstablishmentRejectCode {
    /// `Unnegotiated` (0).
    Unnegotiated,
    /// `AlreadyEstablished` (1).
    AlreadyEstablished,
    /// `SessionBlocked` (2).
    SessionBlocked,
    /// `KeepaliveInterval` (3).
    KeepaliveInterval,
    /// `Credentials` (4).
    Credentials,
    /// `Unspecified` (5).
    Unspecified,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl EstablishmentRejectCode {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            0 => Self::Unnegotiated,
            1 => Self::AlreadyEstablished,
            2 => Self::SessionBlocked,
            3 => Self::KeepaliveInterval,
            4 => Self::Credentials,
            5 => Self::Unspecified,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::Unnegotiated => 0,
            Self::AlreadyEstablished => 1,
            Self::SessionBlocked => 2,
            Self::KeepaliveInterval => 3,
            Self::Credentials => 4,
            Self::Unspecified => 5,
            Self::Unknown(raw) => raw,
        }
    }
}

/// `RetransmitRejectCode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RetransmitRejectCode {
    /// `OutOfRange` (0).
    OutOfRange,
    /// `InvalidSession` (1).
    InvalidSession,
    /// `RequestLimitExceeded` (2).
    RequestLimitExceeded,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl RetransmitRejectCode {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            0 => Self::OutOfRange,
            1 => Self::InvalidSession,
            2 => Self::RequestLimitExceeded,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::OutOfRange => 0,
            Self::InvalidSession => 1,
            Self::RequestLimitExceeded => 2,
            Self::Unknown(raw) => raw,
        }
    }
}

/// `TerminationCode`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TerminationCode {
    /// `Finished` (0).
    Finished,
    /// `UnspecifiedError` (1).
    UnspecifiedError,
    /// `ReRequestOutOfBounds` (2).
    ReRequestOutOfBounds,
    /// `ReRequestInProgress` (3).
    ReRequestInProgress,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl TerminationCode {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            0 => Self::Finished,
            1 => Self::UnspecifiedError,
            2 => Self::ReRequestOutOfBounds,
            3 => Self::ReRequestInProgress,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::Finished => 0,
            Self::UnspecifiedError => 1,
            Self::ReRequestOutOfBounds => 2,
            Self::ReRequestInProgress => 3,
            Self::Unknown(raw) => raw,
        }
    }
}

/// `messageHeader`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MessageHeader {
    /// `blockLength`.
    pub block_length: u16,
    /// `templateId`.
    pub template_id: u16,
    /// `schemaId`.
    pub schema_id: u16,
    /// `version`.
    pub version: u16,
}

impl MessageHeader {
    /// Its size on the wire.
    pub const SIZE: usize = 8;

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            block_length: turbojet::sbe::get_le::<u16>(bytes, 0),
            template_id: turbojet::sbe::get_le::<u16>(bytes, 2),
            schema_id: turbojet::sbe::get_le::<u16>(bytes, 4),
            version: turbojet::sbe::get_le::<u16>(bytes, 6),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_le(bytes, 0, self.block_length);
        turbojet::sbe::put_le(bytes, 2, self.template_id);
        turbojet::sbe::put_le(bytes, 4, self.schema_id);
        turbojet::sbe::put_le(bytes, 6, self.version);
    }
}

/// `Negotiate` (template 1), read where it lies.
#[derive(Clone, Copy)]
pub struct NegotiateRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    credentials: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for NegotiateRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 25;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (credentials, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, credentials }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> NegotiateRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `Timestamp` (2).
    pub fn timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `ClientFlow` (3).
    pub fn client_flow(&self) -> FlowType {
        FlowType::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 24))
    }

    /// `Credentials` (4).
    pub fn credentials(&self) -> &'a [u8] {
        self.credentials
    }
}

impl std::fmt::Debug for NegotiateRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NegotiateRef")
            .field("session_id", &self.session_id())
            .field("timestamp", &self.timestamp())
            .field("client_flow", &self.client_flow())
            .field("credentials", &self.credentials())
            .finish()
    }
}

/// `Negotiate` (template 1), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Negotiate<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `Timestamp` (2).
    pub timestamp: u64,
    /// `ClientFlow` (3).
    pub client_flow: FlowType,
    /// `Credentials` (4).
    pub credentials: &'a [u8],
}

impl Negotiate<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 25;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 1;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 25, template_id: 1, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 25);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.timestamp);
        turbojet::sbe::put_le(block, 24, self.client_flow.raw());
        write_data_u16(out, "Credentials", self.credentials, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for Negotiate<'_> {
    const TEMPLATE_ID: u16 = 1;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Negotiate::encode_into(self, out)
    }
}

/// `NegotiationResponse` (template 2), read where it lies.
#[derive(Clone, Copy)]
pub struct NegotiationResponseRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    credentials: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for NegotiationResponseRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 25;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (credentials, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, credentials }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> NegotiationResponseRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `RequestTimestamp` (5).
    pub fn request_timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `ServerFlow` (6).
    pub fn server_flow(&self) -> FlowType {
        FlowType::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 24))
    }

    /// `Credentials` (4).
    pub fn credentials(&self) -> &'a [u8] {
        self.credentials
    }
}

impl std::fmt::Debug for NegotiationResponseRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NegotiationResponseRef")
            .field("session_id", &self.session_id())
            .field("request_timestamp", &self.request_timestamp())
            .field("server_flow", &self.server_flow())
            .field("credentials", &self.credentials())
            .finish()
    }
}

/// `NegotiationResponse` (template 2), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct NegotiationResponse<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `RequestTimestamp` (5).
    pub request_timestamp: u64,
    /// `ServerFlow` (6).
    pub server_flow: FlowType,
    /// `Credentials` (4).
    pub credentials: &'a [u8],
}

impl NegotiationResponse<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 25;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 2;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 25, template_id: 2, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 25);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.request_timestamp);
        turbojet::sbe::put_le(block, 24, self.server_flow.raw());
        write_data_u16(out, "Credentials", self.credentials, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for NegotiationResponse<'_> {
    const TEMPLATE_ID: u16 = 2;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        NegotiationResponse::encode_into(self, out)
    }
}

/// `NegotiationReject` (template 3), read where it lies.
#[derive(Clone, Copy)]
pub struct NegotiationRejectRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    reason: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for NegotiationRejectRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 25;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (reason, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, reason }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> NegotiationRejectRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `RequestTimestamp` (5).
    pub fn request_timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `Code` (7).
    pub fn code(&self) -> NegotiationRejectCode {
        NegotiationRejectCode::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 24))
    }

    /// `Reason` (8).
    pub fn reason(&self) -> &'a [u8] {
        self.reason
    }
}

impl std::fmt::Debug for NegotiationRejectRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NegotiationRejectRef")
            .field("session_id", &self.session_id())
            .field("request_timestamp", &self.request_timestamp())
            .field("code", &self.code())
            .field("reason", &self.reason())
            .finish()
    }
}

/// `NegotiationReject` (template 3), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct NegotiationReject<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `RequestTimestamp` (5).
    pub request_timestamp: u64,
    /// `Code` (7).
    pub code: NegotiationRejectCode,
    /// `Reason` (8).
    pub reason: &'a [u8],
}

impl NegotiationReject<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 25;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 3;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 25, template_id: 3, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 25);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.request_timestamp);
        turbojet::sbe::put_le(block, 24, self.code.raw());
        write_data_u16(out, "Reason", self.reason, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for NegotiationReject<'_> {
    const TEMPLATE_ID: u16 = 3;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        NegotiationReject::encode_into(self, out)
    }
}

/// `Topic` (template 4), read where it lies.
#[derive(Clone, Copy)]
pub struct TopicRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    classification: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for TopicRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 21;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (classification, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, classification }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> TopicRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `Flow` (8).
    pub fn flow(&self) -> FlowType {
        FlowType::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 16))
    }

    /// `KeepaliveInterval` (9).
    pub fn keepalive_interval(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 17)
    }

    /// `Classification` (10).
    pub fn classification(&self) -> &'a [u8] {
        self.classification
    }
}

impl std::fmt::Debug for TopicRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TopicRef")
            .field("session_id", &self.session_id())
            .field("flow", &self.flow())
            .field("keepalive_interval", &self.keepalive_interval())
            .field("classification", &self.classification())
            .finish()
    }
}

/// `Topic` (template 4), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Topic<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `Flow` (8).
    pub flow: FlowType,
    /// `KeepaliveInterval` (9).
    pub keepalive_interval: u32,
    /// `Classification` (10).
    pub classification: &'a [u8],
}

impl Topic<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 21;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 4;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 21, template_id: 4, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 21);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.flow.raw());
        turbojet::sbe::put_le(block, 17, self.keepalive_interval);
        write_data_u16(out, "Classification", self.classification, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for Topic<'_> {
    const TEMPLATE_ID: u16 = 4;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Topic::encode_into(self, out)
    }
}

/// `Establish` (template 5), read where it lies.
#[derive(Clone, Copy)]
pub struct EstablishRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    credentials: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for EstablishRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 36;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (credentials, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, credentials }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> EstablishRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `Timestamp` (2).
    pub fn timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `KeepaliveInterval` (9).
    pub fn keepalive_interval(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 24)
    }

    /// `NextSeqNo` (11).
    pub fn next_seq_no(&self) -> Option<u64> {
        Some(turbojet::sbe::get_le::<u64>(self.sbe_block, 28)).filter(|v| *v != u64::MAX)
    }

    /// `Credentials` (4).
    pub fn credentials(&self) -> &'a [u8] {
        self.credentials
    }
}

impl std::fmt::Debug for EstablishRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EstablishRef")
            .field("session_id", &self.session_id())
            .field("timestamp", &self.timestamp())
            .field("keepalive_interval", &self.keepalive_interval())
            .field("next_seq_no", &self.next_seq_no())
            .field("credentials", &self.credentials())
            .finish()
    }
}

/// `Establish` (template 5), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Establish<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `Timestamp` (2).
    pub timestamp: u64,
    /// `KeepaliveInterval` (9).
    pub keepalive_interval: u32,
    /// `NextSeqNo` (11).
    pub next_seq_no: Option<u64>,
    /// `Credentials` (4).
    pub credentials: &'a [u8],
}

impl Establish<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 36;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 5;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 36, template_id: 5, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 36);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.timestamp);
        turbojet::sbe::put_le(block, 24, self.keepalive_interval);
        turbojet::sbe::put_le(block, 28, self.next_seq_no.unwrap_or(u64::MAX));
        write_data_u16(out, "Credentials", self.credentials, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for Establish<'_> {
    const TEMPLATE_ID: u16 = 5;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Establish::encode_into(self, out)
    }
}

/// `EstablishmentAck` (template 6), read where it lies.
#[derive(Clone, Copy)]
pub struct EstablishmentAckRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for EstablishmentAckRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 36;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> EstablishmentAckRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `RequestTimestamp` (5).
    pub fn request_timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `KeepaliveInterval` (9).
    pub fn keepalive_interval(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 24)
    }

    /// `NextSeqNo` (11).
    pub fn next_seq_no(&self) -> Option<u64> {
        Some(turbojet::sbe::get_le::<u64>(self.sbe_block, 28)).filter(|v| *v != u64::MAX)
    }
}

impl std::fmt::Debug for EstablishmentAckRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EstablishmentAckRef")
            .field("session_id", &self.session_id())
            .field("request_timestamp", &self.request_timestamp())
            .field("keepalive_interval", &self.keepalive_interval())
            .field("next_seq_no", &self.next_seq_no())
            .finish()
    }
}

/// `EstablishmentAck` (template 6), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct EstablishmentAck {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `RequestTimestamp` (5).
    pub request_timestamp: u64,
    /// `KeepaliveInterval` (9).
    pub keepalive_interval: u32,
    /// `NextSeqNo` (11).
    pub next_seq_no: Option<u64>,
}

impl EstablishmentAck {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 36;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 6;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 36, template_id: 6, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 36);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.request_timestamp);
        turbojet::sbe::put_le(block, 24, self.keepalive_interval);
        turbojet::sbe::put_le(block, 28, self.next_seq_no.unwrap_or(u64::MAX));
        Ok(())
    }
}

impl turbojet::sbe::Encode for EstablishmentAck {
    const TEMPLATE_ID: u16 = 6;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        EstablishmentAck::encode_into(self, out)
    }
}

/// `EstablishmentReject` (template 7), read where it lies.
#[derive(Clone, Copy)]
pub struct EstablishmentRejectRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    reason: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for EstablishmentRejectRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 25;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (reason, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, reason }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> EstablishmentRejectRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `RequestTimestamp` (5).
    pub fn request_timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `Code` (12).
    pub fn code(&self) -> EstablishmentRejectCode {
        EstablishmentRejectCode::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 24))
    }

    /// `Reason` (8).
    pub fn reason(&self) -> &'a [u8] {
        self.reason
    }
}

impl std::fmt::Debug for EstablishmentRejectRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("EstablishmentRejectRef")
            .field("session_id", &self.session_id())
            .field("request_timestamp", &self.request_timestamp())
            .field("code", &self.code())
            .field("reason", &self.reason())
            .finish()
    }
}

/// `EstablishmentReject` (template 7), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct EstablishmentReject<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `RequestTimestamp` (5).
    pub request_timestamp: u64,
    /// `Code` (12).
    pub code: EstablishmentRejectCode,
    /// `Reason` (8).
    pub reason: &'a [u8],
}

impl EstablishmentReject<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 25;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 7;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 25, template_id: 7, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 25);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.request_timestamp);
        turbojet::sbe::put_le(block, 24, self.code.raw());
        write_data_u16(out, "Reason", self.reason, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for EstablishmentReject<'_> {
    const TEMPLATE_ID: u16 = 7;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        EstablishmentReject::encode_into(self, out)
    }
}

/// `Sequence` (template 8), read where it lies.
#[derive(Clone, Copy)]
pub struct SequenceRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for SequenceRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 8;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> SequenceRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `NextSeqNo` (11).
    pub fn next_seq_no(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 0)
    }
}

impl std::fmt::Debug for SequenceRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SequenceRef").field("next_seq_no", &self.next_seq_no()).finish()
    }
}

/// `Sequence` (template 8), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Sequence {
    /// `NextSeqNo` (11).
    pub next_seq_no: u64,
}

impl Sequence {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 8;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 8;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 8, template_id: 8, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 8);
        turbojet::sbe::put_le(block, 0, self.next_seq_no);
        Ok(())
    }
}

impl turbojet::sbe::Encode for Sequence {
    const TEMPLATE_ID: u16 = 8;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Sequence::encode_into(self, out)
    }
}

/// `Context` (template 9), read where it lies.
#[derive(Clone, Copy)]
pub struct ContextRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for ContextRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 24;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> ContextRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `NextSeqNo` (11).
    pub fn next_seq_no(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }
}

impl std::fmt::Debug for ContextRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ContextRef")
            .field("session_id", &self.session_id())
            .field("next_seq_no", &self.next_seq_no())
            .finish()
    }
}

/// `Context` (template 9), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Context {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `NextSeqNo` (11).
    pub next_seq_no: u64,
}

impl Context {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 24;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 9;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 24, template_id: 9, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 24);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.next_seq_no);
        Ok(())
    }
}

impl turbojet::sbe::Encode for Context {
    const TEMPLATE_ID: u16 = 9;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Context::encode_into(self, out)
    }
}

/// `UnsequencedHeartbeat` (template 10), read where it lies.
#[derive(Clone, Copy)]
pub struct UnsequencedHeartbeatRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for UnsequencedHeartbeatRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 0;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> UnsequencedHeartbeatRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }
}

impl std::fmt::Debug for UnsequencedHeartbeatRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("UnsequencedHeartbeatRef").finish()
    }
}

/// `UnsequencedHeartbeat` (template 10), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct UnsequencedHeartbeat {}

impl UnsequencedHeartbeat {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 0;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 10;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 0, template_id: 10, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        turbojet::sbe::reserve(out, 0);
        Ok(())
    }
}

impl turbojet::sbe::Encode for UnsequencedHeartbeat {
    const TEMPLATE_ID: u16 = 10;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        UnsequencedHeartbeat::encode_into(self, out)
    }
}

/// `RetransmitRequest` (template 11), read where it lies.
#[derive(Clone, Copy)]
pub struct RetransmitRequestRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for RetransmitRequestRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 36;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> RetransmitRequestRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `Timestamp` (2).
    pub fn timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `FromSeqNo` (13).
    pub fn from_seq_no(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 24)
    }

    /// `Count` (14).
    pub fn count(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 32)
    }
}

impl std::fmt::Debug for RetransmitRequestRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RetransmitRequestRef")
            .field("session_id", &self.session_id())
            .field("timestamp", &self.timestamp())
            .field("from_seq_no", &self.from_seq_no())
            .field("count", &self.count())
            .finish()
    }
}

/// `RetransmitRequest` (template 11), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct RetransmitRequest {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `Timestamp` (2).
    pub timestamp: u64,
    /// `FromSeqNo` (13).
    pub from_seq_no: u64,
    /// `Count` (14).
    pub count: u32,
}

impl RetransmitRequest {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 36;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 11;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 36, template_id: 11, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 36);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.timestamp);
        turbojet::sbe::put_le(block, 24, self.from_seq_no);
        turbojet::sbe::put_le(block, 32, self.count);
        Ok(())
    }
}

impl turbojet::sbe::Encode for RetransmitRequest {
    const TEMPLATE_ID: u16 = 11;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        RetransmitRequest::encode_into(self, out)
    }
}

/// `Retransmission` (template 12), read where it lies.
#[derive(Clone, Copy)]
pub struct RetransmissionRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for RetransmissionRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 36;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> RetransmissionRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `RequestTimestamp` (5).
    pub fn request_timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `NextSeqNo` (11).
    pub fn next_seq_no(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 24)
    }

    /// `Count` (14).
    pub fn count(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 32)
    }
}

impl std::fmt::Debug for RetransmissionRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RetransmissionRef")
            .field("session_id", &self.session_id())
            .field("request_timestamp", &self.request_timestamp())
            .field("next_seq_no", &self.next_seq_no())
            .field("count", &self.count())
            .finish()
    }
}

/// `Retransmission` (template 12), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Retransmission {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `RequestTimestamp` (5).
    pub request_timestamp: u64,
    /// `NextSeqNo` (11).
    pub next_seq_no: u64,
    /// `Count` (14).
    pub count: u32,
}

impl Retransmission {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 36;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 12;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 36, template_id: 12, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 36);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.request_timestamp);
        turbojet::sbe::put_le(block, 24, self.next_seq_no);
        turbojet::sbe::put_le(block, 32, self.count);
        Ok(())
    }
}

impl turbojet::sbe::Encode for Retransmission {
    const TEMPLATE_ID: u16 = 12;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Retransmission::encode_into(self, out)
    }
}

/// `RestransmitReject` (template 13), read where it lies.
#[derive(Clone, Copy)]
pub struct RestransmitRejectRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    reason: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for RestransmitRejectRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 25;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (reason, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, reason }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> RestransmitRejectRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `RequestTimestamp` (5).
    pub fn request_timestamp(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 16)
    }

    /// `Code` (15).
    pub fn code(&self) -> RetransmitRejectCode {
        RetransmitRejectCode::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 24))
    }

    /// `Reason` (8).
    pub fn reason(&self) -> &'a [u8] {
        self.reason
    }
}

impl std::fmt::Debug for RestransmitRejectRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("RestransmitRejectRef")
            .field("session_id", &self.session_id())
            .field("request_timestamp", &self.request_timestamp())
            .field("code", &self.code())
            .field("reason", &self.reason())
            .finish()
    }
}

/// `RestransmitReject` (template 13), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct RestransmitReject<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `RequestTimestamp` (5).
    pub request_timestamp: u64,
    /// `Code` (15).
    pub code: RetransmitRejectCode,
    /// `Reason` (8).
    pub reason: &'a [u8],
}

impl RestransmitReject<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 25;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 13;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 25, template_id: 13, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 25);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.request_timestamp);
        turbojet::sbe::put_le(block, 24, self.code.raw());
        write_data_u16(out, "Reason", self.reason, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for RestransmitReject<'_> {
    const TEMPLATE_ID: u16 = 13;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        RestransmitReject::encode_into(self, out)
    }
}

/// `Terminate` (template 14), read where it lies.
#[derive(Clone, Copy)]
pub struct TerminateRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    reason: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for TerminateRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 17;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (reason, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, reason }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> TerminateRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `Code` (16).
    pub fn code(&self) -> TerminationCode {
        TerminationCode::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 16))
    }

    /// `Reason` (8).
    pub fn reason(&self) -> &'a [u8] {
        self.reason
    }
}

impl std::fmt::Debug for TerminateRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TerminateRef")
            .field("session_id", &self.session_id())
            .field("code", &self.code())
            .field("reason", &self.reason())
            .finish()
    }
}

/// `Terminate` (template 14), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Terminate<'a> {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `Code` (16).
    pub code: TerminationCode,
    /// `Reason` (8).
    pub reason: &'a [u8],
}

impl Terminate<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 17;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 14;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 17, template_id: 14, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 17);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.code.raw());
        write_data_u16(out, "Reason", self.reason, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for Terminate<'_> {
    const TEMPLATE_ID: u16 = 14;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Terminate::encode_into(self, out)
    }
}

/// `FinishedSending` (template 15), read where it lies.
#[derive(Clone, Copy)]
pub struct FinishedSendingRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for FinishedSendingRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 24;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> FinishedSendingRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }

    /// `LastSeqNo` (17).
    pub fn last_seq_no(&self) -> Option<u64> {
        Some(turbojet::sbe::get_le::<u64>(self.sbe_block, 16)).filter(|v| *v != u64::MAX)
    }
}

impl std::fmt::Debug for FinishedSendingRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FinishedSendingRef")
            .field("session_id", &self.session_id())
            .field("last_seq_no", &self.last_seq_no())
            .finish()
    }
}

/// `FinishedSending` (template 15), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct FinishedSending {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
    /// `LastSeqNo` (17).
    pub last_seq_no: Option<u64>,
}

impl FinishedSending {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 24;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 15;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 24, template_id: 15, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 24);
        block[0..16].copy_from_slice(&self.session_id);
        turbojet::sbe::put_le(block, 16, self.last_seq_no.unwrap_or(u64::MAX));
        Ok(())
    }
}

impl turbojet::sbe::Encode for FinishedSending {
    const TEMPLATE_ID: u16 = 15;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        FinishedSending::encode_into(self, out)
    }
}

/// `FinishedReceiving` (template 16), read where it lies.
#[derive(Clone, Copy)]
pub struct FinishedReceivingRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for FinishedReceivingRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 16;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> FinishedReceivingRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `SessionId` (1).
    pub fn session_id(&self) -> [u8; 16] {
        self.sbe_block[0..16].try_into().expect("a slice of 16")
    }
}

impl std::fmt::Debug for FinishedReceivingRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FinishedReceivingRef").field("session_id", &self.session_id()).finish()
    }
}

/// `FinishedReceiving` (template 16), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct FinishedReceiving {
    /// `SessionId` (1).
    pub session_id: [u8; 16],
}

impl FinishedReceiving {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 16;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 16;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 16, template_id: 16, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 16);
        block[0..16].copy_from_slice(&self.session_id);
        Ok(())
    }
}

impl turbojet::sbe::Encode for FinishedReceiving {
    const TEMPLATE_ID: u16 = 16;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        FinishedReceiving::encode_into(self, out)
    }
}

/// `Applied` (template 17), read where it lies.
#[derive(Clone, Copy)]
pub struct AppliedRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for AppliedRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 12;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> AppliedRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `FromSeqNo` (13).
    pub fn from_seq_no(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 0)
    }

    /// `Count` (14).
    pub fn count(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 8)
    }
}

impl std::fmt::Debug for AppliedRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AppliedRef").field("from_seq_no", &self.from_seq_no()).field("count", &self.count()).finish()
    }
}

/// `Applied` (template 17), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Applied {
    /// `FromSeqNo` (13).
    pub from_seq_no: u64,
    /// `Count` (14).
    pub count: u32,
}

impl Applied {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 12;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 17;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 12, template_id: 17, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 12);
        turbojet::sbe::put_le(block, 0, self.from_seq_no);
        turbojet::sbe::put_le(block, 8, self.count);
        Ok(())
    }
}

impl turbojet::sbe::Encode for Applied {
    const TEMPLATE_ID: u16 = 17;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        Applied::encode_into(self, out)
    }
}

/// `NotApplied` (template 18), read where it lies.
#[derive(Clone, Copy)]
pub struct NotAppliedRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for NotAppliedRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 12;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> NotAppliedRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `FromSeqNo` (13).
    pub fn from_seq_no(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 0)
    }

    /// `Count` (14).
    pub fn count(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 8)
    }
}

impl std::fmt::Debug for NotAppliedRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NotAppliedRef").field("from_seq_no", &self.from_seq_no()).field("count", &self.count()).finish()
    }
}

/// `NotApplied` (template 18), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct NotApplied {
    /// `FromSeqNo` (13).
    pub from_seq_no: u64,
    /// `Count` (14).
    pub count: u32,
}

impl NotApplied {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 12;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 18;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 12, template_id: 18, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 12);
        turbojet::sbe::put_le(block, 0, self.from_seq_no);
        turbojet::sbe::put_le(block, 8, self.count);
        Ok(())
    }
}

impl turbojet::sbe::Encode for NotApplied {
    const TEMPLATE_ID: u16 = 18;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        NotApplied::encode_into(self, out)
    }
}

/// `MessageTemplate` (template 19), read where it lies.
#[derive(Clone, Copy)]
pub struct MessageTemplateRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    version: &'a [u8],
    template: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for MessageTemplateRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 12;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (version, at) = read_data_u16(bytes, at)?;
        let (template, at) = read_data_u16(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, version, template }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> MessageTemplateRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `EncodingType` (18).
    pub fn encoding_type(&self) -> u32 {
        turbojet::sbe::get_le::<u32>(self.sbe_block, 0)
    }

    /// `EffectiveTime` (19).
    pub fn effective_time(&self) -> Option<u64> {
        Some(turbojet::sbe::get_le::<u64>(self.sbe_block, 4)).filter(|v| *v != u64::MAX)
    }

    /// `Version` (20).
    pub fn version(&self) -> &'a [u8] {
        self.version
    }

    /// `Template` (21).
    pub fn template(&self) -> &'a [u8] {
        self.template
    }
}

impl std::fmt::Debug for MessageTemplateRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("MessageTemplateRef")
            .field("encoding_type", &self.encoding_type())
            .field("effective_time", &self.effective_time())
            .field("version", &self.version())
            .field("template", &self.template())
            .finish()
    }
}

/// `MessageTemplate` (template 19), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct MessageTemplate<'a> {
    /// `EncodingType` (18).
    pub encoding_type: u32,
    /// `EffectiveTime` (19).
    pub effective_time: Option<u64>,
    /// `Version` (20).
    pub version: &'a [u8],
    /// `Template` (21).
    pub template: &'a [u8],
}

impl MessageTemplate<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 12;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 19;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 12, template_id: 19, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 12);
        turbojet::sbe::put_le(block, 0, self.encoding_type);
        turbojet::sbe::put_le(block, 4, self.effective_time.unwrap_or(u64::MAX));
        write_data_u16(out, "Version", self.version, u16::MAX)?;
        write_data_u16(out, "Template", self.template, u16::MAX)?;
        Ok(())
    }
}

impl turbojet::sbe::Encode for MessageTemplate<'_> {
    const TEMPLATE_ID: u16 = 19;

    fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        MessageTemplate::encode_into(self, out)
    }
}

/// A message of this schema, as [`decode`] found it.
#[derive(Debug, Clone, Copy)]
pub enum Decoded<'a> {
    /// `Negotiate`.
    Negotiate(NegotiateRef<'a>),
    /// `NegotiationResponse`.
    NegotiationResponse(NegotiationResponseRef<'a>),
    /// `NegotiationReject`.
    NegotiationReject(NegotiationRejectRef<'a>),
    /// `Topic`.
    Topic(TopicRef<'a>),
    /// `Establish`.
    Establish(EstablishRef<'a>),
    /// `EstablishmentAck`.
    EstablishmentAck(EstablishmentAckRef<'a>),
    /// `EstablishmentReject`.
    EstablishmentReject(EstablishmentRejectRef<'a>),
    /// `Sequence`.
    Sequence(SequenceRef<'a>),
    /// `Context`.
    Context(ContextRef<'a>),
    /// `UnsequencedHeartbeat`.
    UnsequencedHeartbeat(UnsequencedHeartbeatRef<'a>),
    /// `RetransmitRequest`.
    RetransmitRequest(RetransmitRequestRef<'a>),
    /// `Retransmission`.
    Retransmission(RetransmissionRef<'a>),
    /// `RestransmitReject`.
    RestransmitReject(RestransmitRejectRef<'a>),
    /// `Terminate`.
    Terminate(TerminateRef<'a>),
    /// `FinishedSending`.
    FinishedSending(FinishedSendingRef<'a>),
    /// `FinishedReceiving`.
    FinishedReceiving(FinishedReceivingRef<'a>),
    /// `Applied`.
    Applied(AppliedRef<'a>),
    /// `NotApplied`.
    NotApplied(NotAppliedRef<'a>),
    /// `MessageTemplate`.
    MessageTemplate(MessageTemplateRef<'a>),
}

/// Reads the message at the start of `bytes`: its header, then the message its template ID names. Returns the message and its length, header included.
///
/// # Errors
///
/// If the header names another schema or an unknown template, or the message doesn't fit in `bytes`.
#[allow(clippy::too_many_lines)]
pub fn decode(bytes: &[u8]) -> Result<(Decoded<'_>, usize), turbojet::sbe::SbeError> {
    let header = MessageHeader::decode(turbojet::sbe::take(bytes, 0, MessageHeader::SIZE)?);
    if header.schema_id != SCHEMA_ID {
        return Err(turbojet::sbe::SbeError::SchemaId(header.schema_id));
    }
    let body = &bytes[MessageHeader::SIZE..];
    let block_length = usize::from(header.block_length);
    let (message, len) = match header.template_id {
        1 => {
            let (message, len) = <NegotiateRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Negotiate(message), len)
        }
        2 => {
            let (message, len) =
                <NegotiationResponseRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::NegotiationResponse(message), len)
        }
        3 => {
            let (message, len) =
                <NegotiationRejectRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::NegotiationReject(message), len)
        }
        4 => {
            let (message, len) = <TopicRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Topic(message), len)
        }
        5 => {
            let (message, len) = <EstablishRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Establish(message), len)
        }
        6 => {
            let (message, len) =
                <EstablishmentAckRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::EstablishmentAck(message), len)
        }
        7 => {
            let (message, len) =
                <EstablishmentRejectRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::EstablishmentReject(message), len)
        }
        8 => {
            let (message, len) = <SequenceRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Sequence(message), len)
        }
        9 => {
            let (message, len) = <ContextRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Context(message), len)
        }
        10 => {
            let (message, len) =
                <UnsequencedHeartbeatRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::UnsequencedHeartbeat(message), len)
        }
        11 => {
            let (message, len) =
                <RetransmitRequestRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::RetransmitRequest(message), len)
        }
        12 => {
            let (message, len) = <RetransmissionRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Retransmission(message), len)
        }
        13 => {
            let (message, len) =
                <RestransmitRejectRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::RestransmitReject(message), len)
        }
        14 => {
            let (message, len) = <TerminateRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Terminate(message), len)
        }
        15 => {
            let (message, len) =
                <FinishedSendingRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::FinishedSending(message), len)
        }
        16 => {
            let (message, len) =
                <FinishedReceivingRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::FinishedReceiving(message), len)
        }
        17 => {
            let (message, len) = <AppliedRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Applied(message), len)
        }
        18 => {
            let (message, len) = <NotAppliedRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::NotApplied(message), len)
        }
        19 => {
            let (message, len) =
                <MessageTemplateRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::MessageTemplate(message), len)
        }
        id => return Err(turbojet::sbe::SbeError::UnknownTemplate(id)),
    };
    Ok((message, MessageHeader::SIZE + len))
}

fn read_data_u16(bytes: &[u8], at: usize) -> Result<(&[u8], usize), turbojet::sbe::SbeError> {
    let len = turbojet::sbe::length(turbojet::sbe::get_le::<u16>(turbojet::sbe::take(bytes, at, 2)?, 0))?;
    Ok((turbojet::sbe::take(bytes, at + 2, len)?, at + 2 + len))
}

fn write_data_u16(out: &mut Vec<u8>, name: &'static str, data: &[u8], max: u16) -> Result<(), turbojet::sbe::SbeError> {
    let len = turbojet::sbe::count(name, data.len(), max)?;
    turbojet::sbe::put_le(turbojet::sbe::reserve(out, 2), 0, len);
    out.extend_from_slice(data);
    Ok(())
}
