// Generated by turbojet-codegen from the SBE schema "baseline" (ID 1, version 0). Don't edit: regenerate.

/// The schema's ID, which each message header carries.
pub const SCHEMA_ID: u16 = 1;
/// The schema's version, which encoded messages carry.
pub const SCHEMA_VERSION: u16 = 0;

/// `BoostType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BoostType {
    /// `TURBO` (b'T').
    Turbo,
    /// `SUPERCHARGER` (b'S').
    Supercharger,
    /// `NITROUS` (b'N').
    Nitrous,
    /// `KERS` (b'K').
    Kers,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl BoostType {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            b'T' => Self::Turbo,
            b'S' => Self::Supercharger,
            b'N' => Self::Nitrous,
            b'K' => Self::Kers,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::Turbo => b'T',
            Self::Supercharger => b'S',
            Self::Nitrous => b'N',
            Self::Kers => b'K',
            Self::Unknown(raw) => raw,
        }
    }
}

/// `BooleanType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BooleanType {
    /// `F` (0).
    F,
    /// `T` (1).
    T,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl BooleanType {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            0 => Self::F,
            1 => Self::T,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::F => 0,
            Self::T => 1,
            Self::Unknown(raw) => raw,
        }
    }
}

/// `Model`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Model {
    /// `A` (b'A').
    A,
    /// `B` (b'B').
    B,
    /// `C` (b'C').
    C,
    /// A value the schema doesn't list.
    Unknown(u8),
}

impl Model {
    /// The value `raw` stands for.
    #[must_use]
    pub fn from_raw(raw: u8) -> Self {
        match raw {
            b'A' => Self::A,
            b'B' => Self::B,
            b'C' => Self::C,
            other => Self::Unknown(other),
        }
    }

    /// Its value on the wire.
    #[must_use]
    pub fn raw(self) -> u8 {
        match self {
            Self::A => b'A',
            Self::B => b'B',
            Self::C => b'C',
            Self::Unknown(raw) => raw,
        }
    }
}

/// `OptionalExtras`: a set of choices, one bit each.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub struct OptionalExtras(pub u8);

impl OptionalExtras {
    /// Whether `sunRoof` (bit 0) is chosen.
    #[must_use]
    pub fn sun_roof(self) -> bool {
        self.0 & (1) != 0
    }

    /// With `sunRoof` (bit 0) chosen or not.
    #[must_use]
    pub fn with_sun_roof(self, on: bool) -> Self {
        if on { Self(self.0 | (1)) } else { Self(self.0 & !(1)) }
    }
    /// Whether `sportsPack` (bit 1) is chosen.
    #[must_use]
    pub fn sports_pack(self) -> bool {
        self.0 & (1 << 1) != 0
    }

    /// With `sportsPack` (bit 1) chosen or not.
    #[must_use]
    pub fn with_sports_pack(self, on: bool) -> Self {
        if on { Self(self.0 | (1 << 1)) } else { Self(self.0 & !(1 << 1)) }
    }
    /// Whether `cruiseControl` (bit 2) is chosen.
    #[must_use]
    pub fn cruise_control(self) -> bool {
        self.0 & (1 << 2) != 0
    }

    /// With `cruiseControl` (bit 2) chosen or not.
    #[must_use]
    pub fn with_cruise_control(self, on: bool) -> Self {
        if on { Self(self.0 | (1 << 2)) } else { Self(self.0 & !(1 << 2)) }
    }
}

/// `messageHeader`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MessageHeader {
    /// `blockLength`.
    pub block_length: u16,
    /// `templateId`.
    pub template_id: u16,
    /// `schemaId`.
    pub schema_id: u16,
    /// `version`.
    pub version: u16,
}

impl MessageHeader {
    /// Its size on the wire.
    pub const SIZE: usize = 8;

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            block_length: turbojet::sbe::get_le::<u16>(bytes, 0),
            template_id: turbojet::sbe::get_le::<u16>(bytes, 2),
            schema_id: turbojet::sbe::get_le::<u16>(bytes, 4),
            version: turbojet::sbe::get_le::<u16>(bytes, 6),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_le(bytes, 0, self.block_length);
        turbojet::sbe::put_le(bytes, 2, self.template_id);
        turbojet::sbe::put_le(bytes, 4, self.schema_id);
        turbojet::sbe::put_le(bytes, 6, self.version);
    }
}

/// `groupSizeEncoding`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct GroupSizeEncoding {
    /// `blockLength`.
    pub block_length: u16,
    /// `numInGroup`.
    pub num_in_group: u16,
}

impl GroupSizeEncoding {
    /// Its size on the wire.
    pub const SIZE: usize = 4;

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            block_length: turbojet::sbe::get_le::<u16>(bytes, 0),
            num_in_group: turbojet::sbe::get_le::<u16>(bytes, 2),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_le(bytes, 0, self.block_length);
        turbojet::sbe::put_le(bytes, 2, self.num_in_group);
    }
}

/// `Booster`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Booster {
    /// `BoostType`.
    pub boost_type: BoostType,
    /// `horsePower`.
    pub horse_power: u8,
}

impl Booster {
    /// Its size on the wire.
    pub const SIZE: usize = 2;

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            boost_type: BoostType::from_raw(turbojet::sbe::get_le::<u8>(bytes, 0)),
            horse_power: turbojet::sbe::get_le::<u8>(bytes, 1),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_le(bytes, 0, self.boost_type.raw());
        turbojet::sbe::put_le(bytes, 1, self.horse_power);
    }
}

/// `Engine`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Engine {
    /// `capacity`.
    pub capacity: u16,
    /// `numCylinders`.
    pub num_cylinders: u8,
    /// `manufacturerCode`.
    pub manufacturer_code: [u8; 3],
    /// `efficiency`.
    pub efficiency: i8,
    /// `boosterEnabled`.
    pub booster_enabled: BooleanType,
    /// `booster`.
    pub booster: Booster,
}

impl Engine {
    /// Its size on the wire.
    pub const SIZE: usize = 10;
    /// `maxRpm`, which is constant.
    pub const MAX_RPM: u16 = 9000;
    /// `fuel`, which is constant.
    pub const FUEL: &'static [u8] = b"Petrol";

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            capacity: turbojet::sbe::get_le::<u16>(bytes, 0),
            num_cylinders: turbojet::sbe::get_le::<u8>(bytes, 2),
            manufacturer_code: bytes[3..6].try_into().expect("a slice of 3"),
            efficiency: turbojet::sbe::get_le::<i8>(bytes, 6),
            booster_enabled: BooleanType::from_raw(turbojet::sbe::get_le::<u8>(bytes, 7)),
            booster: Booster::decode(&bytes[8..]),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_le(bytes, 0, self.capacity);
        turbojet::sbe::put_le(bytes, 2, self.num_cylinders);
        bytes[3..6].copy_from_slice(&self.manufacturer_code);
        turbojet::sbe::put_le(bytes, 6, self.efficiency);
        turbojet::sbe::put_le(bytes, 7, self.booster_enabled.raw());
        self.booster.encode(&mut bytes[8..]);
    }
}

/// `Car` (template 1), read where it lies.
#[derive(Clone, Copy)]
pub struct CarRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    fuel_figures: turbojet::sbe::Group<'a, CarFuelFiguresRef<'a>>,
    performance_figures: turbojet::sbe::Group<'a, CarPerformanceFiguresRef<'a>>,
    manufacturer: &'a [u8],
    model: &'a [u8],
    activation_code: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for CarRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 45;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (fuel_figures, at) = read_group_size_encoding::<CarFuelFiguresRef<'a>>(bytes, at, version)?;
        let (performance_figures, at) = read_group_size_encoding::<CarPerformanceFiguresRef<'a>>(bytes, at, version)?;
        let (manufacturer, at) = read_data_u32(bytes, at)?;
        let (model, at) = read_data_u32(bytes, at)?;
        let (activation_code, at) = read_data_u32(bytes, at)?;
        Ok((
            Self {
                sbe_block,
                sbe_version: version,
                fuel_figures,
                performance_figures,
                manufacturer,
                model,
                activation_code,
            },
            at,
        ))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> CarRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `serialNumber` (1).
    pub fn serial_number(&self) -> u64 {
        turbojet::sbe::get_le::<u64>(self.sbe_block, 0)
    }

    /// `modelYear` (2).
    pub fn model_year(&self) -> u16 {
        turbojet::sbe::get_le::<u16>(self.sbe_block, 8)
    }

    /// `available` (3).
    pub fn available(&self) -> BooleanType {
        BooleanType::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 10))
    }

    /// `code` (4).
    pub fn code(&self) -> Model {
        Model::from_raw(turbojet::sbe::get_le::<u8>(self.sbe_block, 11))
    }

    /// `someNumbers` (5).
    pub fn some_numbers(&self) -> [u32; 4] {
        std::array::from_fn(|i| turbojet::sbe::get_le::<u32>(self.sbe_block, 12 + i * 4))
    }

    /// `vehicleCode` (6).
    pub fn vehicle_code(&self) -> &'a [u8] {
        turbojet::sbe::chars(&self.sbe_block[28..34])
    }

    /// `extras` (7).
    pub fn extras(&self) -> OptionalExtras {
        OptionalExtras(turbojet::sbe::get_le::<u8>(self.sbe_block, 34))
    }

    /// `discountedModel` (8).
    pub fn discounted_model(&self) -> Model {
        Model::C
    }

    /// `engine` (9).
    pub fn engine(&self) -> Engine {
        Engine::decode(&self.sbe_block[35..])
    }

    /// `fuelFigures` (10).
    pub fn fuel_figures(&self) -> turbojet::sbe::Group<'a, CarFuelFiguresRef<'a>> {
        self.fuel_figures
    }

    /// `performanceFigures` (13).
    pub fn performance_figures(&self) -> turbojet::sbe::Group<'a, CarPerformanceFiguresRef<'a>> {
        self.performance_figures
    }

    /// `manufacturer` (18).
    pub fn manufacturer(&self) -> &'a [u8] {
        self.manufacturer
    }

    /// `model` (19).
    pub fn model(&self) -> &'a [u8] {
        self.model
    }

    /// `activationCode` (20).
    pub fn activation_code(&self) -> &'a [u8] {
        self.activation_code
    }
}

impl std::fmt::Debug for CarRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CarRef")
            .field("serial_number", &self.serial_number())
            .field("model_year", &self.model_year())
            .field("available", &self.available())
            .field("code", &self.code())
            .field("some_numbers", &self.some_numbers())
            .field("vehicle_code", &self.vehicle_code())
            .field("extras", &self.extras())
            .field("discounted_model", &self.discounted_model())
            .field("engine", &self.engine())
            .field("fuel_figures", &self.fuel_figures())
            .field("performance_figures", &self.performance_figures())
            .field("manufacturer", &self.manufacturer())
            .field("model", &self.model())
            .field("activation_code", &self.activation_code())
            .finish()
    }
}

/// `Car` (template 1), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Car<'a> {
    /// `serialNumber` (1).
    pub serial_number: u64,
    /// `modelYear` (2).
    pub model_year: u16,
    /// `available` (3).
    pub available: BooleanType,
    /// `code` (4).
    pub code: Model,
    /// `someNumbers` (5).
    pub some_numbers: [u32; 4],
    /// `vehicleCode` (6).
    pub vehicle_code: [u8; 6],
    /// `extras` (7).
    pub extras: OptionalExtras,
    /// `engine` (9).
    pub engine: Engine,
    /// `fuelFigures` (10).
    pub fuel_figures: &'a [CarFuelFigures<'a>],
    /// `performanceFigures` (13).
    pub performance_figures: &'a [CarPerformanceFigures<'a>],
    /// `manufacturer` (18).
    pub manufacturer: &'a [u8],
    /// `model` (19).
    pub model: &'a [u8],
    /// `activationCode` (20).
    pub activation_code: &'a [u8],
}

impl Car<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 45;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 1;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 45, template_id: 1, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 45);
        turbojet::sbe::put_le(block, 0, self.serial_number);
        turbojet::sbe::put_le(block, 8, self.model_year);
        turbojet::sbe::put_le(block, 10, self.available.raw());
        turbojet::sbe::put_le(block, 11, self.code.raw());
        for (i, v) in self.some_numbers.iter().enumerate() {
            turbojet::sbe::put_le(block, 12 + i * 4, *v);
        }
        block[28..34].copy_from_slice(&self.vehicle_code);
        turbojet::sbe::put_le(block, 34, self.extras.0);
        self.engine.encode(&mut block[35..]);
        write_group_size_encoding(out, "fuelFigures", CarFuelFigures::BLOCK_LENGTH, self.fuel_figures.len())?;
        for entry in self.fuel_figures {
            entry.encode_body(out)?;
        }
        write_group_size_encoding(
            out,
            "performanceFigures",
            CarPerformanceFigures::BLOCK_LENGTH,
            self.performance_figures.len(),
        )?;
        for entry in self.performance_figures {
            entry.encode_body(out)?;
        }
        write_data_u32(out, "manufacturer", self.manufacturer, 1073741824)?;
        write_data_u32(out, "model", self.model, 1073741824)?;
        write_data_u32(out, "activationCode", self.activation_code, 1073741824)?;
        Ok(())
    }
}

/// A `CarFuelFigures` entry, read where it lies.
#[derive(Clone, Copy)]
pub struct CarFuelFiguresRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    usage_description: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for CarFuelFiguresRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 6;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (usage_description, at) = read_data_u32(bytes, at)?;
        Ok((Self { sbe_block, sbe_version: _version, usage_description }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> CarFuelFiguresRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `speed` (11).
    pub fn speed(&self) -> u16 {
        turbojet::sbe::get_le::<u16>(self.sbe_block, 0)
    }

    /// `mpg` (12).
    pub fn mpg(&self) -> f32 {
        turbojet::sbe::get_le::<f32>(self.sbe_block, 2)
    }

    /// `usageDescription` (200).
    pub fn usage_description(&self) -> &'a [u8] {
        self.usage_description
    }
}

impl std::fmt::Debug for CarFuelFiguresRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CarFuelFiguresRef")
            .field("speed", &self.speed())
            .field("mpg", &self.mpg())
            .field("usage_description", &self.usage_description())
            .finish()
    }
}

/// A `CarFuelFigures` entry, to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct CarFuelFigures<'a> {
    /// `speed` (11).
    pub speed: u16,
    /// `mpg` (12).
    pub mpg: f32,
    /// `usageDescription` (200).
    pub usage_description: &'a [u8],
}

impl CarFuelFigures<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 6;
    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 6);
        turbojet::sbe::put_le(block, 0, self.speed);
        turbojet::sbe::put_le(block, 2, self.mpg);
        write_data_u32(out, "usageDescription", self.usage_description, 1073741824)?;
        Ok(())
    }
}

/// A `CarPerformanceFigures` entry, read where it lies.
#[derive(Clone, Copy)]
pub struct CarPerformanceFiguresRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    acceleration: turbojet::sbe::Group<'a, CarPerformanceFiguresAccelerationRef<'a>>,
}

impl<'a> turbojet::sbe::Block<'a> for CarPerformanceFiguresRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 1;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (acceleration, at) =
            read_group_size_encoding::<CarPerformanceFiguresAccelerationRef<'a>>(bytes, at, version)?;
        Ok((Self { sbe_block, sbe_version: version, acceleration }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> CarPerformanceFiguresRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `octaneRating` (14).
    pub fn octane_rating(&self) -> u8 {
        turbojet::sbe::get_le::<u8>(self.sbe_block, 0)
    }

    /// `acceleration` (15).
    pub fn acceleration(&self) -> turbojet::sbe::Group<'a, CarPerformanceFiguresAccelerationRef<'a>> {
        self.acceleration
    }
}

impl std::fmt::Debug for CarPerformanceFiguresRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CarPerformanceFiguresRef")
            .field("octane_rating", &self.octane_rating())
            .field("acceleration", &self.acceleration())
            .finish()
    }
}

/// A `CarPerformanceFigures` entry, to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct CarPerformanceFigures<'a> {
    /// `octaneRating` (14).
    pub octane_rating: u8,
    /// `acceleration` (15).
    pub acceleration: &'a [CarPerformanceFiguresAcceleration],
}

impl CarPerformanceFigures<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 1;
    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 1);
        turbojet::sbe::put_le(block, 0, self.octane_rating);
        write_group_size_encoding(
            out,
            "acceleration",
            CarPerformanceFiguresAcceleration::BLOCK_LENGTH,
            self.acceleration.len(),
        )?;
        for entry in self.acceleration {
            entry.encode_body(out)?;
        }
        Ok(())
    }
}

/// A `CarPerformanceFiguresAcceleration` entry, read where it lies.
#[derive(Clone, Copy)]
pub struct CarPerformanceFiguresAccelerationRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for CarPerformanceFiguresAccelerationRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 6;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> CarPerformanceFiguresAccelerationRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `mph` (16).
    pub fn mph(&self) -> u16 {
        turbojet::sbe::get_le::<u16>(self.sbe_block, 0)
    }

    /// `seconds` (17).
    pub fn seconds(&self) -> f32 {
        turbojet::sbe::get_le::<f32>(self.sbe_block, 2)
    }
}

impl std::fmt::Debug for CarPerformanceFiguresAccelerationRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CarPerformanceFiguresAccelerationRef")
            .field("mph", &self.mph())
            .field("seconds", &self.seconds())
            .finish()
    }
}

/// A `CarPerformanceFiguresAcceleration` entry, to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct CarPerformanceFiguresAcceleration {
    /// `mph` (16).
    pub mph: u16,
    /// `seconds` (17).
    pub seconds: f32,
}

impl CarPerformanceFiguresAcceleration {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 6;
    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 6);
        turbojet::sbe::put_le(block, 0, self.mph);
        turbojet::sbe::put_le(block, 2, self.seconds);
        Ok(())
    }
}

/// A message of this schema, as [`decode`] found it.
#[derive(Debug, Clone, Copy)]
pub enum Decoded<'a> {
    /// `Car`.
    Car(CarRef<'a>),
}

/// Reads the message at the start of `bytes`: its header, then the message its template ID names. Returns the message and its length, header included.
///
/// # Errors
///
/// If the header names another schema or an unknown template, or the message doesn't fit in `bytes`.
#[allow(clippy::too_many_lines)]
pub fn decode(bytes: &[u8]) -> Result<(Decoded<'_>, usize), turbojet::sbe::SbeError> {
    let header = MessageHeader::decode(turbojet::sbe::take(bytes, 0, MessageHeader::SIZE)?);
    if header.schema_id != SCHEMA_ID {
        return Err(turbojet::sbe::SbeError::SchemaId(header.schema_id));
    }
    let body = &bytes[MessageHeader::SIZE..];
    let block_length = usize::from(header.block_length);
    let (message, len) = match header.template_id {
        1 => {
            let (message, len) = <CarRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Car(message), len)
        }
        id => return Err(turbojet::sbe::SbeError::UnknownTemplate(id)),
    };
    Ok((message, MessageHeader::SIZE + len))
}

fn read_group_size_encoding<'a, E: turbojet::sbe::Block<'a>>(
    bytes: &'a [u8],
    at: usize,
    version: u16,
) -> Result<(turbojet::sbe::Group<'a, E>, usize), turbojet::sbe::SbeError> {
    let dimension = GroupSizeEncoding::decode(turbojet::sbe::take(bytes, at, GroupSizeEncoding::SIZE)?);
    let at = at + GroupSizeEncoding::SIZE;
    let rest = bytes.get(at..).ok_or(turbojet::sbe::SbeError::Truncated)?;
    let (group, len) = turbojet::sbe::Group::scan(
        rest,
        turbojet::sbe::length(dimension.block_length)?,
        turbojet::sbe::length(dimension.num_in_group)?,
        version,
    )?;
    Ok((group, at + len))
}

fn write_group_size_encoding(
    out: &mut Vec<u8>,
    name: &'static str,
    block_length: usize,
    count: usize,
) -> Result<(), turbojet::sbe::SbeError> {
    let dimension = GroupSizeEncoding {
        block_length: turbojet::sbe::count(name, block_length, u16::MAX)?,
        num_in_group: turbojet::sbe::count(name, count, u16::MAX)?,
    };
    dimension.encode(turbojet::sbe::reserve(out, GroupSizeEncoding::SIZE));
    Ok(())
}

fn read_data_u32(bytes: &[u8], at: usize) -> Result<(&[u8], usize), turbojet::sbe::SbeError> {
    let len = turbojet::sbe::length(turbojet::sbe::get_le::<u32>(turbojet::sbe::take(bytes, at, 4)?, 0))?;
    Ok((turbojet::sbe::take(bytes, at + 4, len)?, at + 4 + len))
}

fn write_data_u32(out: &mut Vec<u8>, name: &'static str, data: &[u8], max: u32) -> Result<(), turbojet::sbe::SbeError> {
    let len = turbojet::sbe::count(name, data.len(), max)?;
    turbojet::sbe::put_le(turbojet::sbe::reserve(out, 4), 0, len);
    out.extend_from_slice(data);
    Ok(())
}
