// Generated by turbojet-codegen from the SBE schema "versioned" (ID 7, version 2). Don't edit: regenerate.

/// The schema's ID, which each message header carries.
pub const SCHEMA_ID: u16 = 7;
/// The schema's version, which encoded messages carry.
pub const SCHEMA_VERSION: u16 = 2;

/// `messageHeader`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct MessageHeader {
    /// `blockLength`.
    pub block_length: u16,
    /// `templateId`.
    pub template_id: u16,
    /// `schemaId`.
    pub schema_id: u16,
    /// `version`.
    pub version: u16,
}

impl MessageHeader {
    /// Its size on the wire.
    pub const SIZE: usize = 8;

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            block_length: turbojet::sbe::get_be::<u16>(bytes, 0),
            template_id: turbojet::sbe::get_be::<u16>(bytes, 2),
            schema_id: turbojet::sbe::get_be::<u16>(bytes, 4),
            version: turbojet::sbe::get_be::<u16>(bytes, 6),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_be(bytes, 0, self.block_length);
        turbojet::sbe::put_be(bytes, 2, self.template_id);
        turbojet::sbe::put_be(bytes, 4, self.schema_id);
        turbojet::sbe::put_be(bytes, 6, self.version);
    }
}

/// `groupSizeEncoding`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct GroupSizeEncoding {
    /// `blockLength`.
    pub block_length: u16,
    /// `numInGroup`.
    pub num_in_group: u16,
}

impl GroupSizeEncoding {
    /// Its size on the wire.
    pub const SIZE: usize = 4;

    /// Reads it from the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    #[must_use]
    pub fn decode(bytes: &[u8]) -> Self {
        Self {
            block_length: turbojet::sbe::get_be::<u16>(bytes, 0),
            num_in_group: turbojet::sbe::get_be::<u16>(bytes, 2),
        }
    }

    /// Writes it at the start of `bytes`.
    ///
    /// # Panics
    ///
    /// If `bytes` is shorter than [`Self::SIZE`].
    pub fn encode(&self, bytes: &mut [u8]) {
        turbojet::sbe::put_be(bytes, 0, self.block_length);
        turbojet::sbe::put_be(bytes, 2, self.num_in_group);
    }
}

/// `Order` (template 1), read where it lies.
#[derive(Clone, Copy)]
pub struct OrderRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
    legs: turbojet::sbe::Group<'a, OrderLegsRef<'a>>,
    note: &'a [u8],
}

impl<'a> turbojet::sbe::Block<'a> for OrderRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = if version >= 2 { 16 } else { if version >= 1 { 8 } else { 4 } };
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        let (legs, at) = if version >= 1 {
            read_group_size_encoding::<OrderLegsRef<'a>>(bytes, at, version)?
        } else {
            (turbojet::sbe::Group::empty(), at)
        };
        let (note, at) = if version >= 2 { read_data_u16(bytes, at)? } else { (&[][..], at) };
        Ok((Self { sbe_block, sbe_version: version, legs, note }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> OrderRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `id` (1).
    pub fn id(&self) -> u32 {
        turbojet::sbe::get_be::<u32>(self.sbe_block, 0)
    }

    /// `qty` (2).
    pub fn qty(&self) -> Option<u32> {
        (self.sbe_version >= 1).then(|| turbojet::sbe::get_be::<u32>(self.sbe_block, 4))
    }

    /// `price` (3).
    pub fn price(&self) -> Option<f64> {
        if self.sbe_version >= 2 {
            Some(turbojet::sbe::get_be::<f64>(self.sbe_block, 8)).filter(|v| !v.is_nan())
        } else {
            None
        }
    }

    /// `legs` (4).
    pub fn legs(&self) -> turbojet::sbe::Group<'a, OrderLegsRef<'a>> {
        self.legs
    }

    /// `note` (6).
    pub fn note(&self) -> &'a [u8] {
        self.note
    }
}

impl std::fmt::Debug for OrderRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OrderRef")
            .field("id", &self.id())
            .field("qty", &self.qty())
            .field("price", &self.price())
            .field("legs", &self.legs())
            .field("note", &self.note())
            .finish()
    }
}

/// `Order` (template 1), to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct Order<'a> {
    /// `id` (1).
    pub id: u32,
    /// `qty` (2).
    pub qty: u32,
    /// `price` (3).
    pub price: Option<f64>,
    /// `legs` (4).
    pub legs: &'a [OrderLegs],
    /// `note` (6).
    pub note: &'a [u8],
}

impl Order<'_> {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 16;
    /// Its template ID.
    pub const TEMPLATE_ID: u16 = 1;

    /// Appends it to `out`, after a message header.
    ///
    /// # Errors
    ///
    /// If a group has more entries, or a data field more bytes, than its encoding allows. `out` is then as it was.
    pub fn encode_into(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let start = out.len();
        let header = MessageHeader { block_length: 16, template_id: 1, schema_id: SCHEMA_ID, version: SCHEMA_VERSION };
        header.encode(turbojet::sbe::reserve(out, MessageHeader::SIZE));
        let result = self.encode_body(out);
        if result.is_err() {
            out.truncate(start);
        }
        result
    }

    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 16);
        turbojet::sbe::put_be(block, 0, self.id);
        turbojet::sbe::put_be(block, 4, self.qty);
        turbojet::sbe::put_be(block, 8, self.price.unwrap_or(f64::NAN));
        write_group_size_encoding(out, "legs", OrderLegs::BLOCK_LENGTH, self.legs.len())?;
        for entry in self.legs {
            entry.encode_body(out)?;
        }
        write_data_u16(out, "note", self.note, 8)?;
        Ok(())
    }
}

/// A `OrderLegs` entry, read where it lies.
#[derive(Clone, Copy)]
pub struct OrderLegsRef<'a> {
    sbe_block: &'a [u8],
    sbe_version: u16,
}

impl<'a> turbojet::sbe::Block<'a> for OrderLegsRef<'a> {
    #[allow(clippy::too_many_lines)]
    fn wrap(bytes: &'a [u8], block_length: usize, _version: u16) -> Result<(Self, usize), turbojet::sbe::SbeError> {
        let sbe_block = turbojet::sbe::take(bytes, 0, block_length)?;
        let needed = 2;
        if block_length < needed {
            return Err(turbojet::sbe::SbeError::BlockLength { actual: block_length, needed });
        }
        let at = block_length;
        Ok((Self { sbe_block, sbe_version: _version }, at))
    }
}

// The methods are named after the schema's fields, whatever their names suggest to clippy.
#[allow(clippy::wrong_self_convention, clippy::should_implement_trait)]
impl<'a> OrderLegsRef<'a> {
    /// The schema version it was encoded in.
    pub fn sbe_version(&self) -> u16 {
        self.sbe_version
    }

    /// `ratio` (5).
    pub fn ratio(&self) -> i16 {
        turbojet::sbe::get_be::<i16>(self.sbe_block, 0)
    }
}

impl std::fmt::Debug for OrderLegsRef<'_> {
    #[allow(clippy::too_many_lines)]
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OrderLegsRef").field("ratio", &self.ratio()).finish()
    }
}

/// A `OrderLegs` entry, to encode.
#[derive(Debug, Clone, PartialEq)]
pub struct OrderLegs {
    /// `ratio` (5).
    pub ratio: i16,
}

impl OrderLegs {
    /// The length of its block.
    pub const BLOCK_LENGTH: usize = 2;
    #[allow(clippy::too_many_lines)]
    fn encode_body(&self, out: &mut Vec<u8>) -> Result<(), turbojet::sbe::SbeError> {
        let block = turbojet::sbe::reserve(out, 2);
        turbojet::sbe::put_be(block, 0, self.ratio);
        Ok(())
    }
}

/// A message of this schema, as [`decode`] found it.
#[derive(Debug, Clone, Copy)]
pub enum Decoded<'a> {
    /// `Order`.
    Order(OrderRef<'a>),
}

/// Reads the message at the start of `bytes`: its header, then the message its template ID names. Returns the message and its length, header included.
///
/// # Errors
///
/// If the header names another schema or an unknown template, or the message doesn't fit in `bytes`.
#[allow(clippy::too_many_lines)]
pub fn decode(bytes: &[u8]) -> Result<(Decoded<'_>, usize), turbojet::sbe::SbeError> {
    let header = MessageHeader::decode(turbojet::sbe::take(bytes, 0, MessageHeader::SIZE)?);
    if header.schema_id != SCHEMA_ID {
        return Err(turbojet::sbe::SbeError::SchemaId(header.schema_id));
    }
    let body = &bytes[MessageHeader::SIZE..];
    let block_length = usize::from(header.block_length);
    let (message, len) = match header.template_id {
        1 => {
            let (message, len) = <OrderRef as turbojet::sbe::Block>::wrap(body, block_length, header.version)?;
            (Decoded::Order(message), len)
        }
        id => return Err(turbojet::sbe::SbeError::UnknownTemplate(id)),
    };
    Ok((message, MessageHeader::SIZE + len))
}

fn read_group_size_encoding<'a, E: turbojet::sbe::Block<'a>>(
    bytes: &'a [u8],
    at: usize,
    version: u16,
) -> Result<(turbojet::sbe::Group<'a, E>, usize), turbojet::sbe::SbeError> {
    let dimension = GroupSizeEncoding::decode(turbojet::sbe::take(bytes, at, GroupSizeEncoding::SIZE)?);
    let at = at + GroupSizeEncoding::SIZE;
    let rest = bytes.get(at..).ok_or(turbojet::sbe::SbeError::Truncated)?;
    let (group, len) = turbojet::sbe::Group::scan(
        rest,
        turbojet::sbe::length(dimension.block_length)?,
        turbojet::sbe::length(dimension.num_in_group)?,
        version,
    )?;
    Ok((group, at + len))
}

fn write_group_size_encoding(
    out: &mut Vec<u8>,
    name: &'static str,
    block_length: usize,
    count: usize,
) -> Result<(), turbojet::sbe::SbeError> {
    let dimension = GroupSizeEncoding {
        block_length: turbojet::sbe::count(name, block_length, u16::MAX)?,
        num_in_group: turbojet::sbe::count(name, count, u16::MAX)?,
    };
    dimension.encode(turbojet::sbe::reserve(out, GroupSizeEncoding::SIZE));
    Ok(())
}

fn read_data_u16(bytes: &[u8], at: usize) -> Result<(&[u8], usize), turbojet::sbe::SbeError> {
    let len = turbojet::sbe::length(turbojet::sbe::get_be::<u16>(turbojet::sbe::take(bytes, at, 2)?, 0))?;
    Ok((turbojet::sbe::take(bytes, at + 2, len)?, at + 2 + len))
}

fn write_data_u16(out: &mut Vec<u8>, name: &'static str, data: &[u8], max: u16) -> Result<(), turbojet::sbe::SbeError> {
    let len = turbojet::sbe::count(name, data.len(), max)?;
    turbojet::sbe::put_be(turbojet::sbe::reserve(out, 2), 0, len);
    out.extend_from_slice(data);
    Ok(())
}
